# Generated by Django 5.2.10 on 2026-10-06 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0007_drop_runtime_and_testflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The dedicated Postgres schema must exist before any of its tables.
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS budget;',
            reverse_sql='DROP SCHEMA IF EXISTS budget CASCADE;',
        ),
        migrations.CreateModel(
            name='BudgetDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('obj_type', models.PositiveSmallIntegerField(choices=[(14, 'A/R credit memo'), (15, 'Delivery'), (18, 'A/P invoice'), (19, 'A/P credit memo'), (28, 'Journal voucher'), (46, 'Outgoing payment'), (59, 'Goods receipt'), (60, 'Goods issue')])),
                ('draft_entry', models.IntegerField()),
                ('doc_num', models.IntegerField(blank=True, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('card_code', models.CharField(blank=True, default='', max_length=50)),
                ('card_name', models.CharField(blank=True, default='', max_length=200)),
                ('sap_created_by', models.CharField(blank=True, default='', max_length=100)),
                ('comments', models.TextField(blank=True, default='')),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('GONE', 'No longer waiting in SAP')], db_index=True, default='PENDING', max_length=10)),
                ('synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budget"."budget_draft',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='budget_draft_co_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'obj_type', 'draft_entry'), name='budget_draft_sap_uq'), models.CheckConstraint(condition=models.Q(('company__in', ('OIL', 'BEVERAGES', 'MART'))), name='budget_draft_company_valid')],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('route', models.CharField(db_index=True, max_length=60)),
                ('budget_code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('GONE', 'No longer waiting in SAP'), ('SUPERSEDED', 'Replaced — the draft changed in SAP')], db_index=True, default='PENDING', max_length=10)),
                ('total_stage', models.PositiveSmallIntegerField(default=0)),
                ('waiting_since', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('sap_status', models.CharField(blank=True, choices=[('SUCCESS', 'Written to SAP'), ('FAILED', 'SAP write failed')], max_length=10, null=True)),
                ('sap_status_text', models.TextField(blank=True, default='')),
                ('sap_written_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budgetdraft')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflow')),
            ],
            options={
                'db_table': 'budget"."budget_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SYNC', 'Taken in from SAP'), ('APPROVE', 'Approved'), ('AUTO_APPROVE', 'Auto-approved'), ('REJECT', 'Rejected'), ('GONE', 'No longer waiting in SAP'), ('SUPERSEDED', 'The draft changed in SAP')], max_length=15)),
                ('remarks', models.TextField(blank=True, default='')),
                ('action_data', models.JSONField(blank=True, default=None, null=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='budget.budgetitem')),
            ],
            options={
                'db_table': 'budget"."budget_action_log',
                'ordering': ['acted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_num', models.IntegerField()),
                ('vis_order', models.IntegerField(blank=True, null=True)),
                ('acct_code', models.CharField(max_length=50)),
                ('acct_name', models.CharField(blank=True, default='', max_length=200)),
                ('budget_code', models.CharField(max_length=50)),
                ('sub_budget_code', models.CharField(blank=True, default='', max_length=50)),
                ('effect_month', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('remarks', models.TextField(blank=True, default='')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budgetdraft')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budgetitem')),
            ],
            options={
                'db_table': 'budget"."budget_line',
                'ordering': ['draft', 'line_num'],
            },
        ),
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_enabled', models.BooleanField(default=False)),
                ('auto_approve_hours', models.PositiveSmallIntegerField(default=48)),
                ('last_sync', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exempt_users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget"."budget_settings',
            },
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['status', 'current_stage'], name='budget_item_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetitem',
            index=models.Index(fields=['company', 'route'], name='budget_item_route_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetitem',
            constraint=models.CheckConstraint(condition=models.Q(('company__in', ('OIL', 'BEVERAGES', 'MART'))), name='budget_item_company_valid'),
        ),
        migrations.AddIndex(
            model_name='budgetactionlog',
            index=models.Index(fields=['item', 'acted_at'], name='budget_log_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('item', 'line_num'), name='budget_line_item_uq'),
        ),
    ]
