# Generated by Django 5.2.10 on 2026-08-03 05:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('upi_reference', models.CharField(blank=True, default='', max_length=60)),
                ('cheque_number', models.CharField(blank=True, default='', max_length=30)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('sap_check_key', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_method_entry',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SapCompanyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('company_db', models.CharField(max_length=100)),
                ('hana_schema', models.CharField(max_length=100)),
                ('default_bpl_id', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SAP company mapping',
                'verbose_name_plural': 'SAP company mappings',
                'db_table': 'payment_sap_company_map',
                'ordering': ['sort_order', 'company'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('account_type', models.CharField(choices=[('BANK', 'Bank'), ('CASH', 'Cash')], default='BANK', max_length=10)),
                ('sap_gl_account', models.CharField(max_length=50)),
                ('sap_house_bank_code', models.CharField(blank=True, default='', max_length=50)),
                ('masked_number', models.CharField(blank=True, default='', max_length=50)),
                ('ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('branch_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_bank_account',
                'ordering': ['company', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'sap_gl_account'), name='payment_bank_gl_per_company_uq')],
            },
        ),
        migrations.CreateModel(
            name='CollectionPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('company', models.CharField(blank=True, choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], default='', max_length=20)),
                ('sap_slp_code', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_collection_person',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit_no', models.CharField(max_length=40, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('company_db', models.CharField(blank=True, default='', max_length=100)),
                ('deposit_date', models.DateField(db_index=True)),
                ('deposit_type', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('MIXED', 'Mixed (cash + cheque)')], default='CASH', max_length=10)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('shortfall_reason', models.TextField(blank=True, default='')),
                ('bank_charge', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('slip_number', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUEUED', 'Queued for SAP'), ('POSTED', 'Posted to SAP'), ('FAILED', 'SAP posting failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('sap_doc_entry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('sap_posted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='payments.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='payments.collectionperson')),
            ],
            options={
                'db_table': 'payment_bank_deposit',
                'ordering': ['-deposit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.PositiveSmallIntegerField(choices=[(10, '₹10'), (20, '₹20'), (50, '₹50'), (100, '₹100'), (200, '₹200'), (500, '₹500')])),
                ('quantity', models.PositiveIntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='payments.paymentmethodentry')),
            ],
            options={
                'db_table': 'payment_cash_denomination',
                'ordering': ['-denomination'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(max_length=40, unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('company_db', models.CharField(blank=True, default='', max_length=100)),
                ('card_code', models.CharField(db_index=True, max_length=50)),
                ('card_name', models.CharField(blank=True, default='', max_length=200)),
                ('received_from_type', models.CharField(choices=[('PARTY', 'Party'), ('PERSON', 'Company person')], default='PARTY', max_length=10)),
                ('payment_date', models.DateField(db_index=True)),
                ('is_advance', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('remarks', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUEUED', 'Queued for SAP'), ('POSTED', 'Posted to SAP'), ('FAILED', 'SAP posting failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('sap_doc_entry', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('sap_posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='payments.bankdeposit')),
                ('received_from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='payments.collectionperson')),
            ],
            options={
                'db_table': 'payment_receipt',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='paymentmethodentry',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='payments.paymentreceipt'),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('invoice_type', models.IntegerField(default=13)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_due_date', models.DateField(blank=True, null=True)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_at_selection', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.paymentreceipt')),
            ],
            options={
                'db_table': 'payment_invoice_allocation',
                'ordering': ['invoice_due_date', 'sap_doc_num'],
            },
        ),
        migrations.CreateModel(
            name='BankDepositLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payments.bankdeposit')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_lines', to='payments.paymentreceipt')),
            ],
            options={
                'db_table': 'payment_bank_deposit_line',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('actor_kind', models.CharField(default='USER', max_length=20)),
                ('changed_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'payment_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SapOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('operation', models.CharField(choices=[('POST_INCOMING_PAYMENT', 'Post incoming payment'), ('POST_DEPOSIT', 'Post deposit')], max_length=30)),
                ('company_db', models.CharField(max_length=100)),
                ('idempotency_key', models.UUIDField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_FLIGHT', 'In flight'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed (retryable)'), ('DEAD', 'Dead (attempts exhausted)'), ('NEEDS_REVIEW', 'Needs manual reconciliation')], db_index=True, default='PENDING', max_length=15)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=6)),
                ('next_attempt_at', models.DateTimeField(db_index=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=64)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_http_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'payment_sap_outbox',
                'ordering': ['next_attempt_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SapCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_db', models.CharField(blank=True, default='', max_length=100)),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('endpoint', models.CharField(max_length=300)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('idempotency_key', models.UUIDField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('sap_error_code', models.CharField(blank=True, default='', max_length=30)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='STARTED', max_length=10)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='payments.sapoutbox')),
            ],
            options={
                'db_table': 'payment_sap_call_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='collectionperson',
            index=models.Index(fields=['company', 'is_active'], name='idx_collperson_company'),
        ),
        migrations.AddIndex(
            model_name='bankdeposit',
            index=models.Index(fields=['company', 'status', '-deposit_date'], name='idx_dep_company_status'),
        ),
        migrations.AddIndex(
            model_name='bankdeposit',
            index=models.Index(fields=['bank_account', '-deposit_date'], name='idx_dep_bank_date'),
        ),
        migrations.AddConstraint(
            model_name='bankdeposit',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gt', 0)), name='bank_deposit_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='bankdeposit',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__lte', models.F('collected_amount'))), name='bank_deposit_not_over_collected'),
        ),
        migrations.AddConstraint(
            model_name='bankdeposit',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount', models.F('collected_amount')), models.Q(('shortfall_reason', ''), _negated=True), _connector='OR'), name='bank_deposit_shortfall_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='cashdenomination',
            constraint=models.UniqueConstraint(fields=('entry', 'denomination'), name='payment_denomination_uq'),
        ),
        migrations.AddConstraint(
            model_name='cashdenomination',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='payment_denomination_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['company', 'status', '-payment_date'], name='idx_rcpt_company_status'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['card_code', 'company'], name='idx_rcpt_party'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['status', 'sap_doc_entry'], name='idx_rcpt_sap'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='payment_receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0), ('allocated_amount__lte', models.F('total_amount'))), name='payment_receipt_allocated_within_total'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('received_from_type', 'PARTY'), ('received_from_person__isnull', False), _connector='OR'), name='payment_receipt_person_required'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethodentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_method_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethodentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('method', 'CHEQUE'), _negated=True), models.Q(models.Q(('cheque_number', ''), _negated=True), ('cheque_date__isnull', False)), _connector='OR'), name='payment_method_cheque_requires_details'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['sap_doc_entry'], name='idx_alloc_docentry'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('receipt', 'sap_doc_entry', 'invoice_type'), name='payment_allocation_uq'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_applied__gt', 0)), name='payment_allocation_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='bankdepositline',
            index=models.Index(fields=['deposit'], name='idx_depline_deposit'),
        ),
        migrations.AddConstraint(
            model_name='bankdepositline',
            constraint=models.UniqueConstraint(fields=('receipt',), name='bank_deposit_receipt_once_uq'),
        ),
        migrations.AddIndex(
            model_name='paymentstatushistory',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='idx_psh_target'),
        ),
        migrations.AddIndex(
            model_name='sapoutbox',
            index=models.Index(fields=['status', 'next_attempt_at'], name='idx_outbox_claimable'),
        ),
        migrations.AddIndex(
            model_name='sapoutbox',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_outbox_target'),
        ),
        migrations.AddConstraint(
            model_name='sapoutbox',
            constraint=models.UniqueConstraint(fields=('operation', 'idempotency_key'), name='payment_outbox_operation_idem_uq'),
        ),
        migrations.AddIndex(
            model_name='sapcalllog',
            index=models.Index(fields=['status', '-created_at'], name='idx_scl_status'),
        ),
        migrations.AddIndex(
            model_name='sapcalllog',
            index=models.Index(fields=['idempotency_key'], name='idx_scl_idem'),
        ),
    ]
