# Generated by Django 5.2.10 on 2026-08-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='sap_house_bank_code',
        ),
    ]
