# Generated by Django 5.2.10 on 2026-08-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0002_remove_bankaccount_sap_house_bank_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sapoutbox',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='sapoutbox',
            name='payment_outbox_operation_idem_uq',
        ),
        migrations.RemoveIndex(
            model_name='sapoutbox',
            name='idx_outbox_claimable',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='last_error',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='last_http_status',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='lease_expires_at',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='sapoutbox',
            name='next_attempt_at',
        ),
        migrations.AddField(
            model_name='sapoutbox',
            name='sap_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUEUED', 'Queued for SAP'), ('POSTED', 'Posted to SAP'), ('PENDING_ERROR', 'Pending error'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('QUEUED', 'Queued for SAP'), ('POSTED', 'Posted to SAP'), ('PENDING_ERROR', 'Pending error'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='sapoutbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.AddIndex(
            model_name='sapoutbox',
            index=models.Index(fields=['status', 'created_at'], name='idx_outbox_claimable'),
        ),
    ]
