# Generated by Django 5.2.10 on 2026-08-04 10:47

import django.db.models.deletion
from django.db import migrations, models


def _carry_sap_response(apps, schema_editor):
    """Copy each document's last SAP response off the outbox before it is dropped.

    `sap_response` now lives ON the document. Without this the reason a payment
    failed would vanish with the table, and the UI would show a PENDING_ERROR
    receipt with no explanation.
    """
    connection = schema_editor.connection
    if 'payment_sap_outbox' not in connection.introspection.table_names():
        return                                  # fresh database — nothing to carry

    with connection.cursor() as cursor:
        for model_name, label in (('paymentreceipt', 'PaymentReceipt'),
                                  ('bankdeposit', 'BankDeposit')):
            table = apps.get_model('payments', label)._meta.db_table
            cursor.execute(f"""
                UPDATE {table} AS d
                SET sap_response = o.sap_response
                FROM payment_sap_outbox AS o
                JOIN django_content_type AS ct ON ct.id = o.content_type_id
                WHERE o.object_id = d.id
                  AND ct.app_label = 'payments'
                  AND ct.model = %s
                  AND COALESCE(o.sap_response, '') <> ''
                  AND COALESCE(d.sap_response, '') = ''
            """, [model_name])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0004_migrate_legacy_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='sap_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(_carry_sap_response, _noop),

        migrations.RemoveField(
            model_name='sapoutbox',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='sapcalllog',
            name='outbox',
        ),
        migrations.RemoveIndex(
            model_name='sapcalllog',
            name='idx_scl_idem',
        ),
        migrations.RemoveField(
            model_name='sapcalllog',
            name='idempotency_key',
        ),
        migrations.AddField(
            model_name='sapcalllog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='sapcalllog',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTING_TO_SAP', 'Posting to SAP'), ('POSTED', 'Posted to SAP'), ('PENDING_ERROR', 'Pending error'), ('SAP_UNKNOWN', 'Awaiting SAP verification'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTING_TO_SAP', 'Posting to SAP'), ('POSTED', 'Posted to SAP'), ('PENDING_ERROR', 'Pending error'), ('SAP_UNKNOWN', 'Awaiting SAP verification'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sapcalllog',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_scl_doc'),
        ),
        migrations.DeleteModel(
            name='SapOutbox',
        ),
    ]
