# Generated by Django 5.2.10 on 2026-08-04 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_migrate_queued_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SapPostingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('action', models.CharField(choices=[('POST_STARTED', 'Post started'), ('POST_SUCCESS', 'Post succeeded'), ('POST_FAILED', 'Post failed'), ('POST_TIMEOUT', 'Post timed out'), ('RESUBMITTED', 'Resubmitted after correction'), ('MANUAL_RECOVERY', 'Manual recovery')], max_length=20)),
                ('status', models.CharField(choices=[('POSTING', 'Posting'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('sap_response', models.TextField(blank=True, default='')),
                ('created_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_posting_history', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_history', to='payments.paymentreceipt')),
            ],
            options={
                'verbose_name': 'SAP posting history',
                'verbose_name_plural': 'SAP posting history',
                'db_table': 'payment_sap_posting_history',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['payment', '-created_at'], name='idx_sph_payment')],
            },
        ),
    ]
