# Generated by Django 5.2.10 on 2026-08-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_drop_dead_queue_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapcompanymap',
            name='cash_gl_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
