# Generated by Django 5.2.10 on 2026-08-06 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_sapcompanymap_cash_gl_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='bank_account',
        ),
        migrations.RemoveIndex(
            model_name='bankdeposit',
            name='idx_dep_bank_date',
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='bank_display_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='bank_gl_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='bank_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='bankdeposit',
            index=models.Index(fields=['bank_gl_account', '-deposit_date'], name='idx_dep_bank_date'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
