# Generated by Django 5.2.10 on 2026-08-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_bankdeposit_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodentry',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank transfer'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentMethodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('bank_key', models.CharField(max_length=80)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_method_mapping',
                'ordering': ['company', 'payment_method', 'priority'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'payment_method'), name='payment_method_mapping_one_active')],
            },
        ),
    ]
