# Generated by Django 5.2.10 on 2026-08-06 10:06

from django.db import migrations, models

# Only cash, UPI and cheque are collected. The three transfer variants were
# never used on a real receipt, so their mappings are configuration for
# tenders that cannot be selected any more.
RETIRED = ['BANK_TRANSFER', 'NEFT', 'RTGS']


def drop_retired_mappings(apps, schema_editor):
    """Delete mappings for methods that no longer exist.

    Safe: no PaymentMethodEntry has ever used one of these, so nothing
    references them. Verified before writing this migration.
    """
    Mapping = apps.get_model('payments', 'PaymentMethodMapping')
    Mapping.objects.filter(payment_method__in=RETIRED).delete()


def noop(apps, schema_editor):
    """Irreversible by design — the mappings pointed at retired methods, and
    recreating them would put back configuration for tenders the form can no
    longer produce. Restoring is a deliberate admin action, not a rollback."""


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_move_to_payments_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodentry',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.RunPython(drop_retired_mappings, noop),
    ]
