# Generated by Django 5.2.10 on 2026-08-06 10:46

from django.db import migrations, models


def backfill_raw_errors(apps, schema_editor):
    """Recover SAP's verbatim words for documents that already failed.

    SapCallLog kept the raw message for any error whose code we had no help
    text for, so those can be copied across exactly. Where the stored message
    WAS rewritten, `_error_text` embedded the original after a "SAP said:"
    marker — so it is still recoverable, and is taken from there rather than
    left blank. Anything neither form matches keeps an empty raw error rather
    than an invented one.
    """
    Receipt = apps.get_model('payments', 'PaymentReceipt')
    Deposit = apps.get_model('payments', 'BankDeposit')
    CallLog = apps.get_model('payments', 'SapCallLog')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for model, label in ((Receipt, 'paymentreceipt'), (Deposit, 'bankdeposit')):
        try:
            ct = ContentType.objects.get(app_label='payments', model=label)
        except ContentType.DoesNotExist:
            continue
        for doc in model.objects.exclude(sap_response=''):
            log = (CallLog.objects
                   .filter(content_type=ct, object_id=doc.pk)
                   .exclude(sap_error_code='')
                   .order_by('-id').first())
            if log is None:
                continue
            text = (log.error_message or '').strip()
            marker = 'SAP said:'
            if marker in text:
                text = text.split(marker, 1)[1].strip()
                # Drop the trailing "SAP code: ..." line we appended.
                text = text.split('\nSAP code:')[0].strip()
            elif '\n\nSAP code:' in text:
                text = text.split('\n\nSAP code:')[0].strip()
            if not text:
                continue
            doc.sap_raw_error = text[:4000]
            doc.sap_raw_error_code = (log.sap_error_code or '')[:20]
            doc.save(update_fields=['sap_raw_error', 'sap_raw_error_code'])


def unbackfill(apps, schema_editor):
    for label in ('PaymentReceipt', 'BankDeposit'):
        apps.get_model('payments', label).objects.update(
            sap_raw_error='', sap_raw_error_code='')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_paymentmethodentry_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='sap_raw_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='sap_raw_error_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_raw_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_raw_error_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sappostinghistory',
            name='sap_raw_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sappostinghistory',
            name='sap_raw_error_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
            migrations.RunPython(backfill_raw_errors, unbackfill),
    ]
