# Generated by Django 5.2.10 on 2026-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_bankdeposit_sap_raw_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_branch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_branch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
