# Generated by Django 5.2.10 on 2026-08-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_paymentreceipt_sap_branch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatushistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted for approval'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned to creator'), ('CANCELLED', 'Cancelled'), ('SAP_POST_STARTED', 'SAP posting started'), ('SAP_POSTED', 'Posted to SAP'), ('SAP_FAILED', 'SAP posting failed'), ('SAP_UNKNOWN', 'SAP outcome unknown'), ('STATUS_CHANGED', 'Status changed')], db_index=True, default='STATUS_CHANGED', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentstatushistory',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentstatushistory',
            name='level_label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='paymentstatushistory',
            name='sap_doc_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentstatushistory',
            name='sap_doc_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
