# Generated by Django 5.2.10 on 2026-08-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_merge_history_into_status_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionperson',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='collectionperson',
            name='sap_slp_code',
        ),
        migrations.RemoveField(
            model_name='collectionperson',
            name='user',
        ),
    ]
