# Generated by Django 5.2.10 on 2026-08-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_remove_collectionperson_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SapPostingHistory',
        ),
    ]
