# Generated by Django 5.2.10 on 2026-08-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_delete_sappostinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='sap_trans_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_trans_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
