# Generated by Django 5.2.10 on 2026-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_add_sap_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapcompanymap',
            name='deposit_source_gl_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
