# Generated by Django 5.2.10 on 2026-08-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_sapcompanymap_deposit_source_gl_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='sap_cancellation_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='sap_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='sap_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_cancellation_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='sap_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTING_TO_SAP', 'Posting to SAP'), ('POSTED', 'Posted to SAP'), ('PENDING_ERROR', 'Pending error'), ('SAP_UNKNOWN', 'Awaiting SAP verification'), ('CANCELLED_IN_SAP', 'Cancelled in SAP'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('POSTING_TO_SAP', 'Posting to SAP'), ('POSTED', 'Posted to SAP'), ('PENDING_ERROR', 'Pending error'), ('SAP_UNKNOWN', 'Awaiting SAP verification'), ('CANCELLED_IN_SAP', 'Cancelled in SAP'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentstatushistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted for approval'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned to creator'), ('CANCELLED', 'Cancelled'), ('SAP_POST_STARTED', 'SAP posting started'), ('SAP_POSTED', 'Posted to SAP'), ('SAP_FAILED', 'SAP posting failed'), ('SAP_UNKNOWN', 'SAP outcome unknown'), ('SAP_CANCELLED', 'Cancelled in SAP'), ('STATUS_CHANGED', 'Status changed')], db_index=True, default='STATUS_CHANGED', max_length=20),
        ),
    ]
