# Generated by Django 5.2.10 on 2026-09-04 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_bankdeposit_sap_cancellation_response_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='verification_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending verification'), ('VERIFIED', 'Verified')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentstatushistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('VERIFIED', 'Verified'), ('SUBMITTED', 'Submitted for approval'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned to creator'), ('CANCELLED', 'Cancelled'), ('SAP_POST_STARTED', 'SAP posting started'), ('SAP_POSTED', 'Posted to SAP'), ('SAP_FAILED', 'SAP posting failed'), ('SAP_UNKNOWN', 'SAP outcome unknown'), ('SAP_CANCELLED', 'Cancelled in SAP'), ('STATUS_CHANGED', 'Status changed')], db_index=True, default='STATUS_CHANGED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['verification_status', '-created_at'], name='idx_rcpt_verification'),
        ),
    ]
