# Generated by Django 5.2.10 on 2026-09-04 07:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_backfill_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethodentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
