# Generated by Django 5.2.10 on 2026-09-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_method_amount_min_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatushistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('VERIFIED', 'Verified'), ('PENDING_APPROVAL', 'Pending approval'), ('SUBMITTED', 'Submitted for approval'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned to creator'), ('CANCELLED', 'Cancelled'), ('SAP_POST_STARTED', 'SAP posting started'), ('SAP_POSTED', 'Posted to SAP'), ('SAP_FAILED', 'SAP posting failed'), ('SAP_UNKNOWN', 'SAP outcome unknown'), ('SAP_CANCELLED', 'Cancelled in SAP'), ('STATUS_CHANGED', 'Status changed')], db_index=True, default='STATUS_CHANGED', max_length=20),
        ),
    ]
