# Generated by Django 5.2.10 on 2026-09-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_history_pending_approval_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatushistory',
            name='change_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
