# Generated by Django 5.2.10 on 2026-09-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_history_change_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='received_from_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
