# Generated by Django 5.2.10 on 2026-09-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_backfill_received_from_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sapcalllog',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='sapcalllog',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='sapcalllog',
            name='sap_doc_entry',
        ),
        migrations.RemoveField(
            model_name='sapcalllog',
            name='sap_doc_num',
        ),
    ]
