# Generated by Django 5.2.10 on 2026-09-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_sapcalllog_drop_duplicate_and_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstatushistory',
            name='actor_kind',
        ),
        migrations.RemoveField(
            model_name='paymentstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='paymentstatushistory',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='paymentstatushistory',
            name='sap_doc_entry',
        ),
        migrations.RemoveField(
            model_name='paymentstatushistory',
            name='sap_doc_num',
        ),
    ]
