# Generated by Django 5.2.10 on 2026-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_history_drop_actor_ip_sapdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodmapping',
            name='gl_account',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentmethodmapping',
            name='bank_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
