# Generated by Django 5.2.10 on 2026-09-05 10:17

"""Drop `payment_sap_company_map`. Every column it held now lives elsewhere.

    company DB / HANA schema -> the environment (payments.sap_company, which
                                delegates to SAPServiceLayerManager.schema_for)
    default_bpl_id           -> HANA_<COMPANY>_DEFAULT_BPL_ID settings
    cash_gl_account          -> PaymentMethodMapping CASH row, migration 0033
    deposit_source_gl_account-> the same cash G/L (one drawer, one account)
    company / display_name /
    is_active / sort_order   -> CATEGORY_CHOICES

Runs AFTER 0033, which copies the cash G/L across — dropping this table first
would destroy the only copy of those accounts.

ONE statement: DROP TABLE "payment_sap_company_map" CASCADE. No payment,
deposit, history, attachment or approval row is read or written, and no SAP
document is touched. Existing receipts and deposits already store their own
`company_db`, frozen at creation, so historical postings keep naming the
company they actually went to.

Irreversible by design: Django can recreate the empty table, but the
configuration it held cannot be reconstructed from anything left behind. The
rows were exported before this was written.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_migrate_cash_gl_to_method_mapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SapCompanyMap',
        ),
    ]
