# Generated by Django 5.2.10 on 2026-09-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_drop_sap_company_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='source_gl_account',
            field=models.CharField(blank=True, db_default='', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentmethodentry',
            name='account_key',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='paymentmethodentry',
            name='account_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmethodentry',
            name='bank_code',
            field=models.CharField(blank=True, db_default='', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentmethodentry',
            name='branch',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentmethodentry',
            name='gl_account',
            field=models.CharField(blank=True, db_default='', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentmethodentry',
            name='receiving_bank_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=150),
        ),
    ]
