# Generated by Django 5.2.10 on 2026-09-18 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0035_receiving_account_snapshot'),
        ('workflow', '0007_drop_runtime_and_testflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatushistory',
            name='stage',
            field=models.ForeignKey(blank=True, db_column='stage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage'),
        ),
        migrations.AlterField(
            model_name='paymentstatushistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('VERIFIED', 'Verified'), ('PENDING_APPROVAL', 'Pending approval'), ('SUBMITTED', 'Submitted for approval'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned to creator'), ('REOPENED', 'Reopened after a SAP failure'), ('CANCELLED', 'Cancelled'), ('SAP_POST_STARTED', 'SAP posting started'), ('SAP_POSTED', 'Posted to SAP'), ('SAP_FAILED', 'SAP posting failed'), ('SAP_UNKNOWN', 'SAP outcome unknown'), ('SAP_CANCELLED', 'Cancelled in SAP'), ('STATUS_CHANGED', 'Status changed')], db_index=True, default='STATUS_CHANGED', max_length=20),
        ),
        migrations.CreateModel(
            name='BankDepositFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('total_stage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(blank=True, db_column='current_stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='payments.bankdeposit')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflow')),
            ],
            options={
                'db_table': 'payment_bank_deposit_flow',
                'indexes': [models.Index(fields=['status', 'current_stage'], name='idx_depflow_queue'), models.Index(fields=['current_stage'], name='idx_depflow_stage')],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceiptFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=12)),
                ('total_stage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(blank=True, db_column='current_stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='payments.paymentreceipt')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflow')),
            ],
            options={
                'db_table': 'payment_receipt_flow',
                'indexes': [models.Index(fields=['status', 'current_stage'], name='idx_rcpflow_queue'), models.Index(fields=['current_stage'], name='idx_rcpflow_stage')],
            },
        ),
    ]
