# Generated by Django 6.0.3 on 2026-05-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_order_is_foc_delete_notification'),
        ('users', '0012_merge_20260511_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='orders.categories'),
        ),
    ]
