# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_company_id_alter_maingroup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
