# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='variety',
            field=models.TextField(blank=True, null=True),
        ),
    ]
