# Generated by Django 6.0.3 on 2026-06-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_sub_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='variety',
        ),
    ]
