# Generated by Django 6.0.3 on 2026-06-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_user_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
