# Generated by Django 5.2.10 on 2026-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_extra_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='extra_pages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
