# Generated by Django 5.2.10 on 2026-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_roles',
            field=models.ManyToManyField(blank=True, help_text='Additional roles beyond the primary one, e.g. Payment Approver.', related_name='extra_users', to='users.userrole'),
        ),
    ]
