# Generated by Django 5.2.10 on 2026-08-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_hais_role'),
        ('users', '0026_partyproductassignment_combo_free_item'),
    ]

    operations = [
    ]
