# Generated by Django 5.2.10 on 2026-08-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_hais_role'),
        ('users', '0027_payment_roles'),
    ]

    operations = [
    ]
