# Generated by Django 5.2.10 on 2026-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_grant_mart_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_id',
            field=models.UUIDField(blank=True, editable=False, help_text="The user's ID in Jivo Auth.", null=True, unique=True),
        ),
    ]
