# Generated by Django 5.2.14 on 2026-05-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0011_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_hand',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
