# Generated by Django 5.2.14 on 2026-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0013_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
