# Generated by Django 6.0.3 on 2026-06-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0015_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='sub_group',
        ),
    ]
