# Generated by Django 6.0.3 on 2026-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0016_rename_type_product_sub_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
