# Generated by Django 5.2.10 on 2026-07-28 06:59

from django.db import migrations


class Migration(migrations.Migration):
    """Key sap_party_addresses the way SAP keys CRD1.

    Two things are off between the model and the database here, so this can't be
    a plain AlterUniqueTogether:

    1. The old ('card_code', 'address_name', 'category') unique constraint is in
       Django's migration state but does not exist in the database — it was
       dropped outside migrations. Letting Django try to drop it raises
       "Found wrong number (0) of constraints", so the removal is state-only.
    2. card_code is declared db_index=True and its varchar_pattern_ops companion
       index survives, but the plain btree index it belongs to is missing. The
       sync's card_code__in lookups sequential-scan without it.
    """

    dependencies = [
        ('sap_sync', '0018_salesorderlog'),
    ]

    operations = [
        # 1. Drop the stale constraint from state only — the database has none.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='partyaddress',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        # 2. Recreate the missing btree index. The name matches what Django
        #    generated originally, so it pairs with the surviving _like index.
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE INDEX IF NOT EXISTS sap_party_addresses_card_code_a42cc6f8 "
                        "ON sap_party_addresses (card_code);"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS sap_party_addresses_card_code_a42cc6f8;"
                    ),
                ),
            ],
        ),
        # 3. Add the real constraint. State says there is none, so Django only
        #    issues the ADD and picks its own conventional name.
        migrations.AlterUniqueTogether(
            name='partyaddress',
            unique_together={('card_code', 'address_name', 'category', 'address_type')},
        ),
    ]
