"""Create the Credit Limit module's own `credit_limit` schema and tables.

No JSAP credit documents are imported; JSAP keeps its history for reference.
"""
# Generated by Django 5.2.10 on 2026-10-05 06:42

import credit_limit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoice", "0025_invoicelog_status_posting"),
        ("workflow", "0008_workflow_priority"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The dedicated schema must exist before any credit_limit"." table.
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS credit_limit;',
            reverse_sql='DROP SCHEMA IF EXISTS credit_limit CASCADE;',
        ),
        migrations.CreateModel(
            name="CreditLimitRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            ("OIL", "Oil"),
                            ("BEVERAGES", "Beverages"),
                            ("MART", "Mart"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("card_code", models.CharField(db_index=True, max_length=50)),
                ("card_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "main_group",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                (
                    "current_credit_limit",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                (
                    "new_credit_limit",
                    models.DecimalField(decimal_places=2, max_digits=19),
                ),
                ("valid_till", models.DateField()),
                ("remarks", models.TextField(blank=True, default="")),
                (
                    "attachment",
                    models.FileField(
                        max_length=500, upload_to=credit_limit.models._attachment_path
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_limit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice_log",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_limit_request",
                        to="invoice.invoicelog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Limit Request",
                "db_table": 'credit_limit"."credit_limit_request',
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditLimitFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("total_stage", models.PositiveSmallIntegerField(default=0)),
                ("sap_payload", models.JSONField(blank=True, default=None, null=True)),
                ("sap_response", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workflow.workflowstage",
                    ),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="workflow.workflow",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flow",
                        to="credit_limit.creditlimitrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Limit Flow",
                "db_table": 'credit_limit"."credit_limit_flow',
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditLimitActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("APPROVE", "Approved"),
                            ("REJECT", "Rejected"),
                        ],
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True, default="")),
                ("acted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "acted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="workflow.workflowstage",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="credit_limit.creditlimitrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Limit Action Log",
                "db_table": 'credit_limit"."credit_limit_action_log',
                "ordering": ["acted_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="creditlimitrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("company__in", ("OIL", "BEVERAGES", "MART"))),
                name="cl_request_company_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="creditlimitrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_credit_limit__gt", 0)),
                name="cl_request_new_limit_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="creditlimitflow",
            index=models.Index(
                fields=["status", "current_stage"], name="cl_flow_queue_idx"
            ),
        ),
    ]
