# Generated by Django 5.2.10 on 2026-10-06 05:50

import credit_limit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_limit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditlimitrequest",
            name="attachment",
            field=models.FileField(
                blank=True,
                default="",
                max_length=500,
                upload_to=credit_limit.models._attachment_path,
            ),
        ),
    ]
