"""Several supporting documents per credit-limit request.

Moves each existing `attachment` into the new table, then drops the column.
"""
# Generated by Django 5.2.10 on 2026-10-07 08:07

import credit_limit.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_attachments(apps, schema_editor):
    Request = apps.get_model('credit_limit', 'CreditLimitRequest')
    Attachment = apps.get_model('credit_limit', 'CreditLimitAttachment')
    Attachment.objects.bulk_create(
        Attachment(request_id=req.pk, file=req.attachment.name,
                   name=req.attachment.name.rsplit('/', 1)[-1][:255],
                   uploaded_by_id=req.created_by_id)
        for req in Request.objects.exclude(attachment='')
    )


def uncopy_attachments(apps, schema_editor):
    """Reverse: put each request's first file back on the column."""
    Request = apps.get_model('credit_limit', 'CreditLimitRequest')
    Attachment = apps.get_model('credit_limit', 'CreditLimitAttachment')
    for row in Attachment.objects.order_by('request_id', 'id'):
        Request.objects.filter(pk=row.request_id, attachment='').update(
            attachment=row.file.name)


class Migration(migrations.Migration):

    dependencies = [
        ("credit_limit", "0002_attachment_optional"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditLimitAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=credit_limit.models._attachment_path
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="credit_limit.creditlimitrequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Limit Attachment",
                "db_table": 'credit_limit"."credit_limit_attachment',
                "ordering": ["request", "id"],
            },
        ),
        # Existing single attachments become rows BEFORE the column goes, so no
        # file a request already carries is lost. The file on disk is untouched.
        migrations.RunPython(copy_attachments, uncopy_attachments),
        migrations.RemoveField(
            model_name="creditlimitrequest",
            name="attachment",
        ),
    ]
