# Generated by Django 5.2.10 on 2026-07-16 07:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('DESKTOP', 'Desktop')], max_length=20)),
                ('app_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('WEB', 'Web'), ('ADMIN_WEB', 'Admin Web'), ('PARTNER_WEB', 'Partner Web'), ('DESKTOP', 'Desktop')], max_length=20)),
                ('version', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Version must be in Major.Minor.Patch form, e.g. 1.2.0.', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('build_number', models.PositiveIntegerField()),
                ('release_notes', models.TextField(blank=True, default='')),
                ('is_latest', models.BooleanField(default=False)),
                ('is_force_update', models.BooleanField(default=False)),
                ('min_supported_version', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Version must be in Major.Minor.Patch form, e.g. 1.2.0.', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('min_supported_build', models.PositiveIntegerField(blank=True, null=True)),
                ('store_url', models.URLField(blank=True, default='')),
                ('released_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Release',
                'db_table': 'devices_app_release',
                'ordering': ['-released_at'],
                'indexes': [models.Index(fields=['platform', 'app_type', 'is_latest'], name='apprelease_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'app_type', 'build_number'), name='apprelease_build_uq'), models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('platform', 'app_type'), name='apprelease_one_latest_uq')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('DESKTOP', 'Desktop')], max_length=20)),
                ('app_type', models.CharField(choices=[('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('WEB', 'Web'), ('ADMIN_WEB', 'Admin Web'), ('PARTNER_WEB', 'Partner Web'), ('DESKTOP', 'Desktop')], max_length=20)),
                ('app_version', models.CharField(max_length=20)),
                ('build_number', models.PositiveIntegerField()),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=50)),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('os_name', models.CharField(blank=True, default='', max_length=20)),
                ('os_version', models.CharField(blank=True, default='', max_length=20)),
                ('browser_name', models.CharField(blank=True, default='', max_length=30)),
                ('browser_version', models.CharField(blank=True, default='', max_length=30)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('first_login', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
                ('last_active', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device',
                'db_table': 'devices_user_device',
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_user_active_idx'), models.Index(fields=['platform', 'app_type', 'build_number'], name='device_plat_build_idx'), models.Index(fields=['last_active'], name='device_last_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='device_user_deviceid_uq')],
            },
        ),
    ]
