# Generated by Django 5.2.10 on 2026-07-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_delete_apprelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=20)),
                ('required_version', models.CharField(max_length=20)),
                ('required_build', models.PositiveIntegerField()),
                ('store_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Version Policy',
                'verbose_name_plural': 'Version Policies',
                'db_table': 'devices_version_policy',
                'ordering': ['platform'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('platform',), name='versionpolicy_one_active_per_platform_uq')],
            },
        ),
    ]
