# Generated by Django 5.2.10 on 2026-09-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_versionpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionpolicy',
            name='required_build',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='versionpolicy',
            name='required_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
