# Generated by Django 5.2.10 on 2026-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('fiscal_year', models.CharField(max_length=9)),
                ('prefix', models.CharField(max_length=20)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_document_counter',
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'company', 'fiscal_year'), name='core_doc_counter_scope_uq')],
            },
        ),
    ]
