# Generated by Django 5.2.10 on 2026-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcounter',
            name='fiscal_year',
            field=models.CharField(max_length=20),
        ),
    ]
