# Generated by Django 5.2.10 on 2026-06-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeldata',
            name='parmeter_json',
        ),
        migrations.AddField(
            model_name='labeldata',
            name='parameter_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
