# Generated by Django 5.2.10 on 2026-06-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_remove_labeldata_parmeter_json_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'label_item',
            },
        ),
        migrations.CreateModel(
            name='NutritionUOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom_name', models.CharField(max_length=25)),
                ('uom_unit', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'nutrition_uom',
            },
        ),
        migrations.CreateModel(
            name='LabelNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrition_name', models.CharField(max_length=125)),
                ('per_serving', models.DecimalField(decimal_places=3, max_digits=7)),
                ('per_100gm', models.DecimalField(decimal_places=3, max_digits=7)),
                ('label_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legal.labelitem')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal.nutritionuom')),
            ],
            options={
                'db_table': 'label_nutrition',
            },
        ),
    ]
