# Generated by Django 5.2.10 on 2026-09-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0003_labelitem_nutritionuom_labelnutrition"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable identifier used as rule_id in the report (e.g. FSSAI_LICENCE). Permanent once reports cite it.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short human name, shown as the checklist heading.",
                        max_length=150,
                    ),
                ),
                (
                    "rule_text",
                    models.TextField(
                        help_text="The rule in plain English, as you would explain it to a reviewer. Sent to the model verbatim."
                    ),
                ),
                (
                    "critical_tokens",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Optional list of literal strings that must appear in the label text, e.g. ["Best Before"]. Case-insensitive. Leave empty unless the rule really does hinge on exact wording.',
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Statutory declarations where a wrong PASS is unacceptable. Only these can have a PASS overturned by the OCR cross-reference.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rules are not sent to the model and do not appear in reports. Deactivate rather than delete, so old reports citing the code stay explicable.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100, help_text="Checklist order. Ties break on code."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "legal_compliance_rule",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="labeldata",
            name="ocr_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labeldata",
            name="report_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
