# Generated by Django 5.2.10 on 2026-09-04 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0005_seed_compliance_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labeldata",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AddField(
            model_name="labeldata",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="label_checks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="labeldata",
            name="label_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="label_checks",
                to="legal.labelitem",
            ),
        ),
        migrations.AddField(
            model_name="labeldata",
            name="preview_image",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
