-- ============================================================================
--  Persistence tables for the NIC e-Invoice (IRN) + e-Way Bill integration.
--  PostgreSQL. Run once against the OMS database (order_management).
--
--  Design notes:
--   * Stores every NIC response artifact (AckNo, AckDt, IRN, SignedInvoice,
--     SignedQRCode) — the IRP purges data after 24h, so this is the taxpayer's
--     record of authentication. (NIC best practice.)
--   * UNIQUE (supplier_gstin, financial_year, doc_type, doc_no) mirrors NIC's
--     one-IRN-per-document rule and prevents duplicate submissions (error 2150).
--   * request_payload / response_payload / error_details kept as JSONB for audit
--     and debugging.
--   * environment distinguishes sandbox vs production rows in one table.
--   * Pairs with Django models declared `managed = False` (see models below).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. e-Invoice / IRN records
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS einvoice_irn (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- environment + soft link back to the OMS order (no hard FK to stay decoupled)
    environment         VARCHAR(10)  NOT NULL DEFAULT 'sandbox',
    order_id            BIGINT       NULL,        -- orders.id, if this IRN maps to an OMS order
    source              VARCHAR(50)  NULL,        -- free label, e.g. 'SAP_INVOICE', 'OMS_ORDER'

    -- document identity == the four IRN hash inputs
    supplier_gstin      VARCHAR(15)  NOT NULL,
    doc_type            VARCHAR(3)   NOT NULL,     -- INV | CRN | DBN
    doc_no              VARCHAR(16)  NOT NULL,
    doc_date            DATE         NOT NULL,
    financial_year      VARCHAR(7)   NOT NULL,     -- e.g. 2025-26
    buyer_gstin         VARCHAR(15)  NULL,         -- 'URP' allowed for exports

    -- internal workflow status
    generation_status   VARCHAR(20)  NOT NULL DEFAULT 'PENDING',  -- PENDING|GENERATED|FAILED|CANCELLED

    -- NIC IRN response
    irn                 VARCHAR(64)  NULL,         -- 64-char SHA-256 hash
    ack_no              VARCHAR(20)  NULL,
    ack_date            TIMESTAMPTZ  NULL,         -- NIC returns IST 'yyyy-MM-dd HH:mm:ss'
    signed_invoice      TEXT         NULL,         -- JWS
    signed_qr_code      TEXT         NULL,         -- JWS (print on invoice)
    irp_status          VARCHAR(3)   NULL,         -- ACT | CNL (from NIC)

    -- e-way bill, if generated together with the IRN
    ewb_no              VARCHAR(15)  NULL,
    ewb_date            TIMESTAMPTZ  NULL,

    -- cancellation (24h window)
    cancelled_at        TIMESTAMPTZ  NULL,
    cancel_reason_code  VARCHAR(1)   NULL,         -- 1=Duplicate 2=Data entry 3=Order cancelled 4=Other
    cancel_remarks      VARCHAR(100) NULL,

    -- audit
    request_payload     JSONB        NULL,         -- invoice JSON we sent
    response_payload    JSONB        NULL,         -- full decrypted NIC response
    error_details       JSONB        NULL,         -- last NIC error list, if failed

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT einvoice_irn_doc_type_chk
        CHECK (doc_type IN ('INV', 'CRN', 'DBN')),
    CONSTRAINT einvoice_irn_env_chk
        CHECK (environment IN ('sandbox', 'production')),
    CONSTRAINT einvoice_irn_status_chk
        CHECK (generation_status IN ('PENDING', 'GENERATED', 'FAILED', 'CANCELLED')),
    -- one IRN per document (NIC rule); scoped by environment so sandbox+prod can coexist
    CONSTRAINT einvoice_irn_doc_uq
        UNIQUE (environment, supplier_gstin, financial_year, doc_type, doc_no),
    CONSTRAINT einvoice_irn_irn_uq
        UNIQUE (irn)
);

CREATE INDEX IF NOT EXISTS einvoice_irn_order_id_idx  ON einvoice_irn (order_id);
CREATE INDEX IF NOT EXISTS einvoice_irn_doc_no_idx     ON einvoice_irn (doc_no);
CREATE INDEX IF NOT EXISTS einvoice_irn_created_at_idx ON einvoice_irn (created_at);
CREATE INDEX IF NOT EXISTS einvoice_irn_gen_status_idx ON einvoice_irn (generation_status);


-- ---------------------------------------------------------------------------
-- 2. e-Way Bill records
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS einvoice_ewaybill (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    environment         VARCHAR(10)  NOT NULL DEFAULT 'sandbox',
    -- link to the IRN row when the EWB was generated via the e-Invoice system
    irn_record_id       BIGINT       NULL REFERENCES einvoice_irn (id) ON DELETE SET NULL,
    order_id            BIGINT       NULL,

    -- EWB response
    ewb_no              VARCHAR(15)  NULL,
    ewb_date            TIMESTAMPTZ  NULL,
    valid_till          TIMESTAMPTZ  NULL,
    ewb_status          VARCHAR(3)   NULL,         -- ACT | CNL

    -- document identity
    supplier_gstin      VARCHAR(15)  NULL,
    buyer_gstin         VARCHAR(15)  NULL,
    doc_type            VARCHAR(15)  NULL,
    doc_no              VARCHAR(16)  NULL,
    doc_date            DATE         NULL,

    -- transport (Part B)
    trans_mode          VARCHAR(1)   NULL,         -- 1=Road 2=Rail 3=Air 4=Ship
    trans_distance      INTEGER      NULL,
    transporter_id      VARCHAR(15)  NULL,
    transporter_name    VARCHAR(100) NULL,
    trans_doc_no        VARCHAR(15)  NULL,
    trans_doc_date      DATE         NULL,
    vehicle_no          VARCHAR(15)  NULL,
    vehicle_type        VARCHAR(1)   NULL,         -- R=Regular O=ODC
    part_b_updated      BOOLEAN      NOT NULL DEFAULT FALSE,

    generation_status   VARCHAR(20)  NOT NULL DEFAULT 'PENDING',  -- PENDING|GENERATED|FAILED|CANCELLED

    -- cancellation (24h window)
    cancelled_at        TIMESTAMPTZ  NULL,
    cancel_reason_code  VARCHAR(2)   NULL,
    cancel_remarks      VARCHAR(100) NULL,

    -- audit
    request_payload     JSONB        NULL,
    response_payload    JSONB        NULL,
    error_details       JSONB        NULL,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT einvoice_ewb_env_chk
        CHECK (environment IN ('sandbox', 'production')),
    CONSTRAINT einvoice_ewb_status_chk
        CHECK (generation_status IN ('PENDING', 'GENERATED', 'FAILED', 'CANCELLED')),
    CONSTRAINT einvoice_ewb_no_uq
        UNIQUE (ewb_no)
);

CREATE INDEX IF NOT EXISTS einvoice_ewb_irn_record_idx ON einvoice_ewaybill (irn_record_id);
CREATE INDEX IF NOT EXISTS einvoice_ewb_order_id_idx    ON einvoice_ewaybill (order_id);
CREATE INDEX IF NOT EXISTS einvoice_ewb_created_at_idx  ON einvoice_ewaybill (created_at);


-- ---------------------------------------------------------------------------
-- 3. Keep updated_at current at the DB level (needed if rows are written by
--    raw SQL rather than the Django ORM). Safe to skip if you always write via
--    the ORM with auto_now=True.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION einvoice_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS einvoice_irn_set_updated_at ON einvoice_irn;
CREATE TRIGGER einvoice_irn_set_updated_at
    BEFORE UPDATE ON einvoice_irn
    FOR EACH ROW EXECUTE FUNCTION einvoice_set_updated_at();

DROP TRIGGER IF EXISTS einvoice_ewb_set_updated_at ON einvoice_ewaybill;
CREATE TRIGGER einvoice_ewb_set_updated_at
    BEFORE UPDATE ON einvoice_ewaybill
    FOR EACH ROW EXECUTE FUNCTION einvoice_set_updated_at();
