"""Create the PRDO module's own `production` PostgreSQL schema and tables.

No JSAP production data is imported by this or any later migration. The module
starts empty and fills from SAP on the first `sync_production_orders` run;
JSAP keeps its 2,868 planned orders / 2,680 flows for reference. The BEHAVIOUR
was migrated, the rows were not — see `docs/backend/PRDO_DESIGN.md`.
"""
# Generated by Django 5.2.10 on 2026-09-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0007_drop_runtime_and_testflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The dedicated Postgres schema must exist before any
        # production"." table is created. IF NOT EXISTS makes it safe
        # to re-run; the reverse drops it only once every table in it
        # has been removed by the unwinds above (CASCADE guards
        # against a half-rolled-back state).
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS production;',
            reverse_sql='DROP SCHEMA IF EXISTS production CASCADE;',
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, help_text='The SAP company database this order belongs to.', max_length=20)),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('item_group', models.CharField(blank=True, default='', max_length=50)),
                ('item_series', models.IntegerField(blank=True, null=True)),
                ('warehouse', models.CharField(blank=True, default='', max_length=20)),
                ('planned_qty', models.DecimalField(decimal_places=6, max_digits=19)),
                ('sal_factor2', models.DecimalField(blank=True, decimal_places=6, help_text='OITM.SalFactor2 — pieces per box, at sync time.', max_digits=19, null=True)),
                ('sal_pack_un', models.DecimalField(blank=True, decimal_places=6, help_text='OITM.SalPackUn — volume per piece, at sync time.', max_digits=19, null=True)),
                ('order_type', models.CharField(choices=[('S', 'Standard'), ('P', 'Special'), ('D', 'Disassembly')], default='S', max_length=1)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('batch_no', models.CharField(blank=True, default='', max_length=50)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('sap_created_by', models.CharField(blank=True, default='', max_length=100)),
                ('sap_user_sign', models.SmallIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('sap_status', models.CharField(choices=[('P', 'Planned'), ('R', 'Released'), ('L', 'Closed'), ('C', 'Cancelled')], db_index=True, default='P', max_length=1)),
                ('synced_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Order',
                'db_table': 'production"."production_order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'sap_status'], name='prdo_company_status_idx'), models.Index(fields=['item_code'], name='prdo_item_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'sap_doc_entry'), name='production_order_sap_uq'), models.CheckConstraint(condition=models.Q(('company__in', ('OIL', 'BEVERAGES', 'MART'))), name='production_order_company_valid'), models.CheckConstraint(condition=models.Q(('order_type__in', ['S', 'P', 'D'])), name='production_order_type_valid'), models.CheckConstraint(condition=models.Q(('sap_status__in', ['P', 'R', 'L', 'C'])), name='production_order_sap_status_valid'), models.CheckConstraint(condition=models.Q(('planned_qty__gt', 0)), name='production_order_qty_positive')],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SYNC', 'Synced from SAP'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('OBSOLETE', 'Retired — no longer planned in SAP')], max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('action_data', models.JSONField(blank=True, default=None, null=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='production.productionorder')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
            ],
            options={
                'verbose_name': 'Production Order Action Log',
                'db_table': 'production"."production_order_action_logs',
                'ordering': ['acted_at', 'id'],
                'indexes': [models.Index(fields=['production_order', 'acted_at'], name='prdo_log_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OBSOLETE', 'No longer planned in SAP')], db_index=True, default='PENDING', max_length=10)),
                ('sap_status', models.CharField(blank=True, choices=[('SUCCESS', 'Written to SAP'), ('FAILED', 'SAP write failed')], max_length=10, null=True)),
                ('sap_payload', models.JSONField(blank=True, default=None, null=True)),
                ('sap_status_text', models.TextField(blank=True, default='')),
                ('total_stage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(blank=True, db_column='current_stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='production.productionorder')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Production Order Flow',
                'db_table': 'production"."production_order_flow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'current_user'], name='prdo_flow_queue_idx'), models.Index(fields=['current_stage'], name='prdo_flow_stage_idx'), models.Index(fields=['workflow'], name='prdo_flow_workflow_idx')],
            },
        ),
    ]
