"""
Mirror IRN records into a custom HANA table (EINVOICE_IRN) in the SAP company
schema, including the signed QR rendered as a PNG (QR_PNG BLOB).

Uses the direct hdbcli connection (hana.services.connection.HANAConnection), not
the Service Layer. Everything here is best-effort: a HANA failure must never
break IRN generation, so callers wrap these and ignore errors (they're logged).

Table is created by `manage.py setup_hana_irn_table --schema <COMPANY_DB>`.
"""
from __future__ import annotations

import json
import logging

from django.conf import settings

from . import qr as qrgen

logger = logging.getLogger(__name__)

TABLE = "EINVOICE_IRN"

# Column order used by both INSERT and the DDL.
_COLUMNS = [
    "ENVIRONMENT", "ORDER_ID", "DOCENTRY", "SOURCE",
    "SUPPLIER_GSTIN", "DOC_TYPE", "DOC_NO", "DOC_DATE", "FINANCIAL_YEAR", "BUYER_GSTIN",
    "GENERATION_STATUS", "IRN", "ACK_NO", "ACK_DATE",
    "SIGNED_INVOICE", "SIGNED_QR_CODE", "QR_PNG", "IRP_STATUS",
    "EWB_NO", "EWB_DATE", "REQUEST_PAYLOAD", "RESPONSE_PAYLOAD", "ERROR_DETAILS",
    "CREATED_AT", "UPDATED_AT",
]

DDL = """
CREATE COLUMN TABLE "{schema}"."{table}" (
  ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ENVIRONMENT NVARCHAR(10),
  ORDER_ID BIGINT,
  DOCENTRY INTEGER,
  SOURCE NVARCHAR(50),
  SUPPLIER_GSTIN NVARCHAR(15),
  DOC_TYPE NVARCHAR(3),
  DOC_NO NVARCHAR(16),
  DOC_DATE DATE,
  FINANCIAL_YEAR NVARCHAR(7),
  BUYER_GSTIN NVARCHAR(15),
  GENERATION_STATUS NVARCHAR(20),
  IRN NVARCHAR(64),
  ACK_NO NVARCHAR(20),
  ACK_DATE TIMESTAMP,
  SIGNED_INVOICE NCLOB,
  SIGNED_QR_CODE NCLOB,
  QR_PNG BLOB,
  IRP_STATUS NVARCHAR(3),
  EWB_NO NVARCHAR(15),
  EWB_DATE TIMESTAMP,
  REQUEST_PAYLOAD NCLOB,
  RESPONSE_PAYLOAD NCLOB,
  ERROR_DETAILS NCLOB,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP,
  PRIMARY KEY (ID)
)
"""

UNIQUE_INDEX_DDL = (
    'CREATE UNIQUE INDEX "{table}_DOC_UQ" ON "{schema}"."{table}" '
    "(ENVIRONMENT, SUPPLIER_GSTIN, FINANCIAL_YEAR, DOC_TYPE, DOC_NO)"
)


def _schema(schema: str | None) -> str:
    return schema or getattr(settings, "HANA_COMPANY_DB", "")


def table_exists(conn, schema: str) -> bool:
    rows = conn.execute(
        "SELECT 1 FROM SYS.TABLES WHERE SCHEMA_NAME = ? AND TABLE_NAME = ?",
        [schema, TABLE],
    )
    return bool(rows)


def create_table(conn, schema: str) -> bool:
    """Create EINVOICE_IRN (+ unique index) in `schema` if absent. Returns True if created."""
    if table_exists(conn, schema):
        return False
    conn.execute(DDL.format(schema=schema, table=TABLE))
    try:
        conn.execute(UNIQUE_INDEX_DDL.format(schema=schema, table=TABLE))
    except Exception:  # noqa: BLE001 — index is a nicety; table already usable
        logger.warning("EINVOICE_IRN created but unique index failed in %s", schema)
    return True


def _dt(v):
    """hdbcli wants naive datetimes for TIMESTAMP columns."""
    if v is None:
        return None
    return v.replace(tzinfo=None) if getattr(v, "tzinfo", None) else v


def _json(v):
    return json.dumps(v, default=str) if v not in (None, "") else None


def _row_values(record, docentry, qr_png):
    return [
        record.environment, record.order_id, docentry, record.source,
        record.supplier_gstin, record.doc_type, record.doc_no, record.doc_date,
        record.financial_year, record.buyer_gstin,
        record.generation_status, record.irn, record.ack_no, _dt(record.ack_date),
        record.signed_invoice, record.signed_qr_code, qr_png, record.irp_status,
        record.ewb_no, _dt(record.ewb_date),
        _json(record.request_payload), _json(record.response_payload), _json(record.error_details),
        _dt(record.created_at), _dt(record.updated_at),
    ]


def mirror_record(record, *, schema: str | None = None, docentry=None) -> bool:
    """
    Upsert an IrnRecord into HANA (delete-by-identity then insert), storing the
    QR as a PNG blob. Best-effort — returns True on success, False on any failure.
    """
    from hana.services.connection import HANAConnection

    schema = _schema(schema)
    if not schema:
        logger.warning("HANA mirror skipped: no schema/company DB configured")
        return False

    # Render the signed QR to PNG bytes (skip if none / lib missing).
    qr_png = None
    if record.signed_qr_code:
        try:
            qr_png = qrgen.make_qr_png(record.signed_qr_code)
        except qrgen.QrUnavailable:
            logger.warning("qrcode library unavailable — storing IRN without QR_PNG")

    cols = ", ".join(_COLUMNS)
    placeholders = ", ".join(["?"] * len(_COLUMNS))
    try:
        with HANAConnection() as conn:
            if not table_exists(conn, schema):
                logger.warning("HANA mirror skipped: %s.%s does not exist (run setup_hana_irn_table)",
                               schema, TABLE)
                return False
            conn.execute(
                f'DELETE FROM "{schema}"."{TABLE}" WHERE ENVIRONMENT = ? AND SUPPLIER_GSTIN = ? '
                f"AND FINANCIAL_YEAR = ? AND DOC_TYPE = ? AND DOC_NO = ?",
                [record.environment, record.supplier_gstin, record.financial_year,
                 record.doc_type, record.doc_no],
            )
            conn.execute(
                f'INSERT INTO "{schema}"."{TABLE}" ({cols}) VALUES ({placeholders})',
                _row_values(record, docentry, qr_png),
            )
        return True
    except Exception:  # noqa: BLE001
        logger.exception("Failed to mirror IRN %s to HANA schema %s", record.doc_no, schema)
        return False
