"""
Persistence for the NIC e-Invoice (IRN) + e-Way Bill integration.

Stores every NIC response artifact (AckNo, AckDt, IRN, SignedInvoice,
SignedQRCode / EWB No, validity) alongside the request payload for audit — the
IRP purges data after 24h, so this is the taxpayer's record of authentication
(NIC best practice). See einvoice/docs/NIC_EINVOICE_EWAYBILL_REFERENCE.md.
"""
from django.db import models


ENVIRONMENT_CHOICES = (("sandbox", "Sandbox"), ("production", "Production"))
GENERATION_STATUS_CHOICES = (
    ("PENDING", "Pending"),
    ("GENERATED", "Generated"),
    ("FAILED", "Failed"),
    ("CANCELLED", "Cancelled"),
)


class IrnRecord(models.Model):
    """One e-Invoice document reported to the IRP → one IRN."""

    DOC_TYPE_CHOICES = (("INV", "Invoice"), ("CRN", "Credit Note"), ("DBN", "Debit Note"))

    environment = models.CharField(max_length=10, choices=ENVIRONMENT_CHOICES, default="sandbox")
    # Soft link to the OMS order (no hard FK to keep the app decoupled).
    order_id = models.BigIntegerField(null=True, blank=True, db_index=True)
    source = models.CharField(max_length=50, null=True, blank=True)  # e.g. 'SAP_INVOICE'

    # Document identity == the four IRN-hash inputs.
    supplier_gstin = models.CharField(max_length=15)
    doc_type = models.CharField(max_length=3, choices=DOC_TYPE_CHOICES)
    doc_no = models.CharField(max_length=16, db_index=True)
    doc_date = models.DateField()
    financial_year = models.CharField(max_length=7)  # e.g. 2025-26
    buyer_gstin = models.CharField(max_length=15, null=True, blank=True)  # 'URP' for exports

    generation_status = models.CharField(
        max_length=20, choices=GENERATION_STATUS_CHOICES, default="PENDING", db_index=True
    )

    # NIC IRN response.
    irn = models.CharField(max_length=64, null=True, blank=True, unique=True)
    ack_no = models.CharField(max_length=20, null=True, blank=True)
    ack_date = models.DateTimeField(null=True, blank=True)  # NIC returns IST
    signed_invoice = models.TextField(null=True, blank=True)  # JWS
    signed_qr_code = models.TextField(null=True, blank=True)  # JWS (print on invoice)
    irp_status = models.CharField(max_length=3, null=True, blank=True)  # ACT | CNL

    # e-Way Bill generated together with the IRN, if any.
    ewb_no = models.CharField(max_length=15, null=True, blank=True)
    ewb_date = models.DateTimeField(null=True, blank=True)

    # Cancellation (24h window). Reason: 1=Duplicate 2=Data entry 3=Order cancelled 4=Other.
    cancelled_at = models.DateTimeField(null=True, blank=True)
    cancel_reason_code = models.CharField(max_length=1, null=True, blank=True)
    cancel_remarks = models.CharField(max_length=100, null=True, blank=True)

    # Audit.
    request_payload = models.JSONField(null=True, blank=True)   # invoice JSON we sent
    response_payload = models.JSONField(null=True, blank=True)  # full decrypted NIC response
    error_details = models.JSONField(null=True, blank=True)     # last NIC error list, if failed

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "einvoice_irn"
        verbose_name = "IRN Record"
        ordering = ["-created_at"]
        constraints = [
            # One IRN per document (NIC rule); scoped by environment so
            # sandbox and production rows can coexist.
            models.UniqueConstraint(
                fields=["environment", "supplier_gstin", "financial_year", "doc_type", "doc_no"],
                name="einvoice_irn_doc_uq",
            ),
        ]

    def __str__(self):
        return f"{self.doc_type} {self.doc_no} → {self.irn or self.generation_status}"


class EwayBill(models.Model):
    """An e-Way Bill (standalone or generated by IRN)."""

    environment = models.CharField(max_length=10, choices=ENVIRONMENT_CHOICES, default="sandbox")
    # Link to the IRN row when the EWB was generated via the e-Invoice system.
    irn_record = models.ForeignKey(
        IrnRecord,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        db_column="irn_record_id",
        related_name="eway_bills",
    )
    order_id = models.BigIntegerField(null=True, blank=True, db_index=True)

    # EWB response.
    ewb_no = models.CharField(max_length=15, null=True, blank=True, unique=True)
    ewb_date = models.DateTimeField(null=True, blank=True)
    valid_till = models.DateTimeField(null=True, blank=True)
    ewb_status = models.CharField(max_length=3, null=True, blank=True)  # ACT | CNL

    # Document identity.
    supplier_gstin = models.CharField(max_length=15, null=True, blank=True)
    buyer_gstin = models.CharField(max_length=15, null=True, blank=True)
    doc_type = models.CharField(max_length=15, null=True, blank=True)
    doc_no = models.CharField(max_length=16, null=True, blank=True)
    doc_date = models.DateField(null=True, blank=True)

    # Transport (Part B). Mode: 1=Road 2=Rail 3=Air 4=Ship. VehType: R=Regular O=ODC.
    trans_mode = models.CharField(max_length=1, null=True, blank=True)
    trans_distance = models.IntegerField(null=True, blank=True)
    transporter_id = models.CharField(max_length=15, null=True, blank=True)
    transporter_name = models.CharField(max_length=100, null=True, blank=True)
    trans_doc_no = models.CharField(max_length=15, null=True, blank=True)
    trans_doc_date = models.DateField(null=True, blank=True)
    vehicle_no = models.CharField(max_length=15, null=True, blank=True)
    vehicle_type = models.CharField(max_length=1, null=True, blank=True)
    part_b_updated = models.BooleanField(default=False)

    generation_status = models.CharField(
        max_length=20, choices=GENERATION_STATUS_CHOICES, default="PENDING", db_index=True
    )

    # Cancellation (24h window).
    cancelled_at = models.DateTimeField(null=True, blank=True)
    cancel_reason_code = models.CharField(max_length=2, null=True, blank=True)
    cancel_remarks = models.CharField(max_length=100, null=True, blank=True)

    # Audit.
    request_payload = models.JSONField(null=True, blank=True)
    response_payload = models.JSONField(null=True, blank=True)
    error_details = models.JSONField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "einvoice_ewaybill"
        verbose_name = "e-Way Bill"
        ordering = ["-created_at"]

    def __str__(self):
        return f"EWB {self.ewb_no or self.generation_status}"


class IrnGenerationLog(models.Model):
    """
    Audit log of every automatic (and manual) IRN generation attempt for a SAP
    invoice DocEntry — one row per attempt, so a failure records exactly what
    went wrong (NIC error code/message or pre-submit validation issues).

    Lives in the order_management DB. Separate from IrnRecord (which holds the
    authoritative successful IRN); this table is the operational trail for the
    automation.
    """

    OUTCOME_CHOICES = (
        ("SUCCESS", "Success"),
        ("FAILED", "Failed"),
        ("SKIPPED", "Skipped"),        # already had an IRN / not eligible
    )
    TRIGGER_CHOICES = (
        ("invoice_create", "Invoice Created"),  # fired from the OMS invoice-create flow
        ("poll", "Polling Job"),                # scheduled sweep
        ("manual", "Manual"),                   # re-run from UI / command
        ("retry", "Retry"),
    )

    docentry = models.IntegerField(db_index=True)
    company_db = models.CharField(max_length=100, null=True, blank=True)
    environment = models.CharField(max_length=10, choices=ENVIRONMENT_CHOICES, default="sandbox")
    trigger = models.CharField(max_length=20, choices=TRIGGER_CHOICES, default="manual", db_index=True)
    attempt_no = models.PositiveIntegerField(default=1)

    outcome = models.CharField(max_length=10, choices=OUTCOME_CHOICES, db_index=True)

    # what got produced (on success)
    doc_no = models.CharField(max_length=16, null=True, blank=True)
    irn = models.CharField(max_length=64, null=True, blank=True)
    ack_no = models.CharField(max_length=20, null=True, blank=True)
    irn_record = models.ForeignKey(
        IrnRecord, on_delete=models.SET_NULL, null=True, blank=True,
        related_name="generation_logs",
    )

    # why it failed
    error_code = models.CharField(max_length=20, null=True, blank=True)
    error_message = models.TextField(null=True, blank=True)
    validation_errors = models.JSONField(null=True, blank=True)  # pre-submit issues, if any

    duration_ms = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = "einvoice_irn_generation_log"
        verbose_name = "IRN Generation Log"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["docentry", "-created_at"]),
            models.Index(fields=["outcome", "-created_at"]),
        ]

    def __str__(self):
        return f"[{self.outcome}] DocEntry {self.docentry} ({self.trigger})"
