# Generated by Django 5.2.10 on 2026-09-30 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'control_panel_main_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'control_panel_state',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('main_group', 'Main Group'), ('state', 'State'), ('person', 'Person'), ('premium_item', 'Premium Items'), ('commodity_item', 'Commodity Items')], max_length=20)),
                ('segment_value', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_realise_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'control_panel_segment_target',
                'ordering': ['segment_type', 'segment_value'],
                'indexes': [models.Index(fields=['segment_type', 'year', 'month'], name='cp_starget_period_idx')],
                'unique_together': {('segment_type', 'segment_value', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TargetNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_group', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('segment', models.CharField(blank=True, default='', max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_realise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'control_panel_target_node',
                'ordering': ['main_group', 'state', 'sales_person'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_tnode_period_idx')],
                'unique_together': {('main_group', 'state', 'sales_person', 'segment', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_head', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('budget_amount', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_panel_expense_budget',
                'ordering': ['budget_head'],
                'unique_together': {('budget_head', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sub_group', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('tgt_ltrs', models.FloatField(default=0)),
                ('tgt_rate', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_panel_monthly_target',
                'ordering': ['-year', '-month', 'product_type', 'sub_group'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_mtarget_period_idx'), models.Index(fields=['product_type', 'sub_group'], name='cp_mtarget_group_idx')],
                'unique_together': {('product_type', 'sub_group', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TargetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(blank=True, max_length=100, null=True)),
                ('target_ltrs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.maingroupmaster')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_panel.statemaster')),
            ],
            options={
                'db_table': 'control_panel_target_master',
                'ordering': ['-year', '-month', 'main_group__name', 'state__name', 'sales_person'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_tmaster_period_idx'), models.Index(fields=['main_group'], name='cp_tmaster_group_idx')],
                'unique_together': {('main_group', 'state', 'sales_person', 'month', 'year')},
            },
        ),
    ]
