"""
Django settings for OMS project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers as cors_default_headers
from decouple import config


def _parse_bool(value, default=False):
    if value is None:
        return default
    if isinstance(value, bool):
        return value

    # Tolerate an inline "# comment" after the value — python-decouple does NOT
    # strip these, so "true   # note" would otherwise parse as neither true nor false.
    normalized = str(value).split('#', 1)[0].strip().lower()
    if normalized in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized in {'0', 'false', 'no', 'off', '', 'release'}:
        return False
    return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# SECRET_KEY = config('SECRET_KEY')
DEBUG = _parse_bool(config('DEBUG', default='false'), default=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#im8s6vmxe)=%xl8$ybjl*fu9(+2=5cf^8$=ok8%bx%0f&^t05'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['138.252.101.118', '10.10.101.118', '127.0.0.1', '10.0.2.2', 'localhost', '192.168.1.240','*']
CSRF_TRUSTED_ORIGINS = ['https://oms.jivo.in' , 'http://oms.jivo.in']
# ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    # 'rest_framework.authtoken',
    # 'rest_framework.authto
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_apscheduler',
    # Local apps
    'users',
    'orders',
    'sap_sync',
    'hana',
    'SKU',
    'serviceLayer',
    # NIC e-Invoice (IRN) + e-Way Bill (ported from the standalone IRN project)
    'einvoice',
    'ewaybill',
    'invoice',
    'legal',
    'audit',
    'devices',
    # Document (invoice) tracker — self-contained, no FKs into OMS models
    'tracker',
    # Dynamic UI labels — admin-editable field labels served to web + mobile
    'uilabels',
    # Receive Payment / Bank Deposit. `core` holds the shared base model and
    # document-number generator; `approvals` is the generic multi-level engine
    # (usable by any document type); `attachments` stores files on the existing
    # shared network folders.
    'core',
    'approvals',
    'attachments',
    'payments',
    # Reusable notification framework. Empty skeleton for now — Orders still
    # owns and serves every notification. Registered ahead of any behaviour so
    # this INSTALLED_APPS change is bisectable on its own.
    'notifications',
    # HAIS — Hardware Asset Identification Software. Owns its own `hais`
    # Postgres schema (created by its initial migration), same as payments.
    'HAIS',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditMiddleware',
    # Mobile Version Policy: blocks out-of-date ANDROID/IOS clients with HTTP
    # 426. Placed AFTER CorsMiddleware so it never interferes with the browser
    # preflight, and only ever acts on requests carrying a mobile X-Platform
    # header — the web is never gated.
    'devices.version_policy.VersionPolicyMiddleware',
]

ROOT_URLCONF = 'OMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'OPTIONS': {
            # The payments module owns its own PostgreSQL schema, so its 19
            # tables group together in pgAdmin instead of being scattered
            # through `public` alongside orders, users and Django's own.
            #
            # `payments` comes FIRST so unqualified names resolve there, and
            # `public` stays on the path because everything else — users_user,
            # django_content_type, the FKs those tables point at — still lives
            # there. Dropping public would break every cross-schema join.
            'options': '-c search_path=payments,public',
        },
    },
    'hana': {
        'ENGINE': 'django.db.backends.dummy',
        'HOST': config('HANA_DB_HOST'),
        'PORT': config('HANA_DB_PORT'),
        # Default HANA schema / company DB used by raw queries
        # (hana/services/connection.py:60, tracker/sap.py:21).
        # `.env` has historically defined this as HANA_DB_OIL_NAME, so accept
        # that (and HANA_COMPANY_DB, which holds the same value) rather than
        # requiring a duplicate HANA_DB_NAME key. Explicit HANA_DB_NAME still
        # wins if it is set.
        'SCHEMA': config(
            'HANA_DB_NAME',
            default=config(
                'HANA_DB_OIL_NAME',
                default=config('HANA_COMPANY_DB', default=''),
            ),
        ),
        'OIL_SCHEMA': config('HANA_DB_OIL_NAME'),
        # Same story as SCHEMA above: `.env` carries the beverage company DB as
        # HANA_BEVERAGE_COMPANY_DB / HANA_COMPANY_DB_BEVERAGES, and has
        # HANA_DB_BEVERAGE_NAME commented out. Fall back through those instead
        # of hard-requiring a key that isn't set, which stops Django booting.
        'BEVERAGE_SCHEMA': config(
            'HANA_DB_BEVERAGE_NAME',
            default=config(
                'HANA_BEVERAGE_COMPANY_DB',
                default=config('HANA_COMPANY_DB_BEVERAGES', default=''),
            ),
        ),
        'MART_SCHEMA': config('HANA_DB_MART_NAME', default=''),
        'USER': config('HANA_DB_USER'),
        'PASSWORD': config('HANA_DB_PASSWORD'),
    },
    
    
}

#HAND credentials
HANA_SERVICE_LAYER_URL = HANA_SERVICE_LAYER_URL = config('HANA_SERVICE_LAYER_URL')
HANA_USERNAME = config('HANA_USERNAME')
HANA_PASSWORD = config('HANA_PASSWORD')
CRYSTAL_URL = config('CRYSTAL_URL')

# Dedicated Service Layer user for Sales Order creation (falls back to the
# default Service Layer user when not configured).
SALES_ORDER_USER = config('SALES_ORDER_USER', default=HANA_USERNAME)
SALES_ORDER_PASSWORD = config('SALES_ORDER_PASSWORD', default=HANA_PASSWORD)

HANA_OIL_COMPANY_DB = config('HANA_DB_OIL_NAME')
# Same fallback chain as DATABASES['hana']['BEVERAGE_SCHEMA'] above. `.env`
# carries this value under any of three names and has had each of them
# commented out at different times, so requiring one outright stops Django
# booting — which is exactly what a bare config() call here did.
HANA_BEVERAGE_COMPANY_DB = config(
    'HANA_BEVERAGE_COMPANY_DB',
    default=config(
        'HANA_DB_BEVERAGE_NAME',
        default=config('HANA_COMPANY_DB_BEVERAGES',
                       default='JIVO_BEVERAGES_HANADB'),
    ),
)
# Third company (Mart). Blank disables everything Mart-specific.
# The .env defines this as HANA_DB_MART_NAME (matching HANA_DB_OIL_NAME /
# HANA_DB_BEVERAGE_NAME); keep the legacy HANA_MART_COMPANY_DB name as a
# fallback so older environments keep working.
HANA_MART_COMPANY_DB = config(
    'HANA_DB_MART_NAME',
    default=config('HANA_MART_COMPANY_DB', default='JIVO_MART_HANADB'),
)
# Profit center (OPRC.PrcCode) to stamp on Mart sales-order lines. Mart does not
# use per-sub_group profit centers like Oil/Beverage, so this is a single code.
# Blank (default) omits CostingCode entirely, letting SAP apply its own default
# profit center (General Center). Set e.g. 'Centr_z' to force an explicit one.
HANA_MART_COSTING_CODE = config('HANA_MART_COSTING_CODE', default='')

# --- JSAP (budget approval) SQL Server -------------------------------------
# Read-only source for budget-approval status of a SAP *draft* document.
# Blank host disables every JSAP lookup (the tracker degrades to "unknown").
JSAP_DB_HOST = config('JSAP_DB_HOST', default='')
JSAP_DB_PORT = config('JSAP_DB_PORT', default=1433, cast=int)
JSAP_DB_NAME = config('JSAP_DB_NAME', default='')
JSAP_DB_USER = config('JSAP_DB_USER', default='')
JSAP_DB_PASSWORD = config('JSAP_DB_PASSWORD', default='')


HANA_COMPANY_DB_BEVERAGES = config('HANA_COMPANY_DB_BEVERAGES', default='')
HANA_WAREHOUSE_CODE = config('HANA_WAREHOUSE_CODE', default='GP-FG')
HANA_WAREHOUSE_CODE_BEVERAGES = config('HANA_WAREHOUSE_CODE_BEVERAGES', default='')
# In DEBUG, default to False for local/self-signed SAP endpoints unless explicitly set.
HANA_SSL_VERIFY = config('HANA_SSL_VERIFY', default=not DEBUG, cast=bool)
HANA_SSL_CA_BUNDLE = config('HANA_SSL_CA_BUNDLE', default='')
HANA_CONNECT_TIMEOUT = config('HANA_CONNECT_TIMEOUT', default=15, cast=int)
HANA_READ_TIMEOUT = config('HANA_READ_TIMEOUT', default=120, cast=int)

# DSR credit-limit service (external project; proxied because it has no CORS)
DSR_API_BASE = config('JSAP_API_BASE')
# Fixed OMS user id stamped as createdBy on DSR credit-limit requests.
OMS_JSAP_USER_ID = config('OMS_JSAP_USER_ID', default=0, cast=int)

# SAP SQL Server (source for sync)
SAP_DB_HOST = config('SAP_DB_HOST', default='138.252.101.118')
SAP_DB_PORT = config('SAP_DB_PORT', default=1433, cast=int)
SAP_DB_NAME = config('SAP_DB_NAME', default='Jivo_All_Branches_Live')
SAP_DB_USER = config('SAP_DB_USER', default='ab')
SAP_DB_PASSWORD = config('SAP_DB_PASSWORD', default='Jivo@!@#$')

# JSAP SQL Server — the DSR/JSAP application's own database. Read-only here; used
# to resolve a credit-limit document to its approval flow id without paging the
# DSR document-list API. Same host as the SAP box, different database.
JSAP_DB_HOST = config('JSAP_DB_HOST', default='103.89.45.75')
JSAP_DB_PORT = config('JSAP_DB_PORT', default=1433, cast=int)
JSAP_DB_NAME = config('JSAP_DB_NAME', default='jsaplive3')
JSAP_DB_USER = config('JSAP_DB_USER', default='ab')
JSAP_DB_PASSWORD = config('JSAP_DB_PASSWORD', default='Jivo@!@#$')

# VAPID (Web Push) keys are configured lower down in this file — see the
# "Web Push (VAPID)" section near the bottom.
SAP_APPROVER_USER = config('SAP_APPROVER_USER')
SAP_APPROVER_PASSWORD = config('SAP_APPROVER_PASSWORD') 


# SAP_DRAFTER = 
# SAP_DRAFTER_PASS = 
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'users.User'

# Existing tables use 32-bit integer primary keys, so keep AutoField as the
# project-wide default (this also silences models.W042). Apps that need 64-bit
# ids (e.g. einvoice) opt in via default_auto_field = BigAutoField in apps.py.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Tells WhiteNoise to compress and aggressively cache your static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# JWT Settings (SimpleJWT). Hardened for production while preserving the
# existing API contract and token compatibility.
SIMPLE_JWT = {
    # Access lifetime kept at 1 day: the current web/mobile clients do NOT run
    # a refresh flow, so shortening this would log active users out mid-session
    # (a compatibility break). Shorten once clients adopt the /auth/refresh/
    # endpoint added in this phase.
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # Rotation + blacklist: a refresh issues a new refresh token and the old
    # one is blacklisted so it cannot be replayed.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Stamp user.last_login on token issuance.
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    # Defaults to SECRET_KEY (so all EXISTING tokens stay valid). Override with
    # a dedicated JWT_SIGNING_KEY in production via .env. Rotating this key
    # invalidates every issued token, so only change it deliberately.
    'SIGNING_KEY': config('JWT_SIGNING_KEY', default=SECRET_KEY),

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    # Small clock-skew tolerance for token exp/nbf validation.
    'LEEWAY': 10,
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

CORS_ALLOW_ALL_ORIGINS = True

# ---------------------------------------------------------------------------
# Email (SMTP) — used by the tracker's stuck-invoice alert emails.
# All from .env; blank host falls back to the console backend so nothing breaks
# in dev. See `manage.py email_stuck_alerts`.
# ---------------------------------------------------------------------------
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = _parse_bool(config('EMAIL_USE_TLS', default='true'), default=True)
EMAIL_USE_SSL = _parse_bool(config('EMAIL_USE_SSL', default='false'), default=False)
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default=('django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST
             else 'django.core.mail.backends.console.EmailBackend'),
)
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default=(EMAIL_HOST_USER or 'oms-tracker@jivo.com'))

# Re-notify cooldown (hours): how long before the same stuck invoice emails the
# stage's users again. Prevents the periodic sweep from spamming.
TRACKER_ALERT_EMAIL_COOLDOWN_HOURS = config(
    'TRACKER_ALERT_EMAIL_COOLDOWN_HOURS', default=24, cast=int)


# CORS_ALLOW_ALL_ORIGINS wildcards the ORIGIN only — it does NOT allow arbitrary
# request HEADERS. The web client attaches device/version metadata headers to
# every request (see Frontend-web/src/services/webDeviceService.ts), and those
# are non-simple headers, so the browser sends a CORS preflight first. Any header
# missing from this list makes the browser reject the preflight and CANCEL the
# real request — it never reaches Django, so it looks like the server is down
# (0 bytes transferred, no response headers) rather than like a CORS error.
#
# Only affects browsers: the React Native client is not subject to CORS.
CORS_ALLOW_HEADERS = (
    *cors_default_headers,
    'x-app-version',
    'x-build-number',
    'x-platform',
    'x-app-type',
    'x-os-version',
    'x-device-id',
)


# =========================================================================
# NIC e-Invoice (IRN) + e-Way Bill configuration
# Ported from the standalone IRN project. The einvoice/ewaybill apps read
# these two dicts off `settings`. Values come from .env (python-decouple).
#
# Sandbox (test) and production credentials both live in .env under the same
# variable names — comment/uncomment the appropriate block per server. So
# switching environments is a .env edit only; no code or setting changes here.
#
# The session AuthToken + SEK are cached in Django's default (LocMemCache)
# cache; switch CACHES to Redis for multi-process/Gunicorn deployments.
# =========================================================================
def _split_urls(raw, fallback=''):
    return [u.strip().rstrip('/') for u in (raw or fallback).split(',') if u.strip()]


# ---- NIC e-Invoice ----
EINV = {
    "BASE_URL": config('EINV_BASE_URL', default='https://einv1api.gstsandbox.nic.in'),
    # Failover hosts (NIC runs a load-balanced pair); comma-separated in .env.
    "BASE_URLS": _split_urls(
        config('EINV_BASE_URLS', default=''),
        'https://einv1api.gstsandbox.nic.in,https://einv2api.gstsandbox.nic.in',
    ),
    "AUTH_PATH": config('EINV_AUTH_PATH', default='/eivital/v1.04/auth'),
    "IRN_PATH": config('EINV_IRN_PATH', default='/eicore/v1.03/Invoice'),
    "CANCEL_PATH": config('EINV_CANCEL_PATH', default='/eicore/v1.03/Invoice/Cancel'),
    "MASTER_GSTIN_PATH": config('EINV_MASTER_GSTIN_PATH', default='/eivital/v1.04/Master/gstin'),
    "SYNC_GSTIN_PATH": config('EINV_SYNC_GSTIN_PATH', default='/eivital/v1.04/Master/syncgstin'),
    "EWB_PATH": config('EINV_EWB_PATH', default='/eiewb/v1.03/ewaybill'),
    "HEARTBEAT_PATH": config('EINV_HEARTBEAT_PATH', default='/eivital/v1.04/heartbeat/ping'),
    "CLIENT_ID": config('EINV_CLIENT_ID', default=''),
    "CLIENT_SECRET": config('EINV_CLIENT_SECRET', default=''),
    "USERNAME": config('EINV_USERNAME', default=''),
    "PASSWORD": config('EINV_PASSWORD', default=''),
    "GSTIN": config('EINV_GSTIN', default=''),
    "PUBLIC_KEY_PATH": config(
        'EINV_PUBLIC_KEY_PATH',
        default=str(BASE_DIR / 'secrets' / 'PublicKey' / 'einv_sandbox.pem'),
    ),
}

# ---- Multi-GSTIN NIC credentials (same PAN, different state GSTINs) ----
# client-id/secret are reusable across GSTINs of one PAN; the API username/password
# are per-GSTIN (created on the e-invoice portal under each GSTIN). List the GSTINs
# in EINV_GSTINS, then add per-GSTIN vars (see .env). The generate/cancel flow picks
# the credential set that matches each invoice's seller GSTIN.
EINV_GSTINS = [g.strip() for g in config('EINV_GSTINS', default='').split(',') if g.strip()]
EINV_CREDENTIALS = {
    g: {
        "GSTIN": g,
        "USERNAME": config(f'EINV_{g}_USERNAME', default=''),
        "PASSWORD": config(f'EINV_{g}_PASSWORD', default=''),
        "CLIENT_ID": config(f'EINV_{g}_CLIENT_ID', default=EINV["CLIENT_ID"]),
        "CLIENT_SECRET": config(f'EINV_{g}_CLIENT_SECRET', default=EINV["CLIENT_SECRET"]),
        "PUBLIC_KEY_PATH": config(f'EINV_{g}_PUBLIC_KEY_PATH', default=EINV["PUBLIC_KEY_PATH"]),
    }
    for g in EINV_GSTINS
}

# When true, creating a real invoice (serviceLayer.SAPInvoiceCreateView, type=INVOICE)
# fires automatic IRN generation for that DocEntry in the background. Every attempt
# is recorded in einvoice_irn_generation_log. Off by default — enable in .env.
EINV_AUTO_GENERATE = _parse_bool(config('EINV_AUTO_GENERATE', default='false'), default=False)

# After an IRN generation attempt:
#  - EINV_MIRROR_HANA: write the attempt into the HANA table OMS_IRN_LOG
#    (same column shape as the SAP add-on's @UTL_MDEXTH): 'S' on success,
#    'F' on failure, and a cancel stamp on cancellation.
#  - EINV_SAP_WRITEBACK: PATCH the IRN back onto the SAP invoice's e-Billing
#    protocol so SAP shows it as e-invoiced (validate on sandbox first).
# Both off by default and best-effort (never break IRN generation).
EINV_MIRROR_HANA = _parse_bool(config('EINV_MIRROR_HANA', default='false'), default=False)
EINV_SAP_WRITEBACK = _parse_bool(config('EINV_SAP_WRITEBACK', default='false'), default=False)

# Also write the IRN QR as a .png FILE into this directory on every generation.
# Point it at the Windows share on another server, e.g.
#   EINV_QR_SAVE_DIR=\\JIVO-APP\OMS_Attachments\Bitmap
# Blank = disabled. {doc_no}, {irn}, {ack_no}, {env} are substituted into the name.
EINV_QR_SAVE_DIR = config('EINV_QR_SAVE_DIR', default='')
EINV_QR_FILENAME = config('EINV_QR_FILENAME', default='{doc_no}.png')

# Per-company QR folders. The IRN's QR PNG is written into the folder of the
# company DB the invoice belongs to, so each company's bitmaps stay separate:
#   \\JIVO-APP\OMS_Attachments\OIL_ATTACHMENTS\Bitmap
#   \\JIVO-APP\OMS_Attachments\BEVERAGE_ATTACHMENTS\Bitmap
#   \\JIVO-APP\OMS_Attachments\MART_ATTACHMENTS\Bitmap
# A blank entry falls back to EINV_QR_SAVE_DIR.
_EINV_QR_ROOT = config('EINV_QR_ROOT', default=r'\\JIVO-APP\OMS_Attachments')
EINV_QR_SAVE_DIRS = {
    HANA_OIL_COMPANY_DB: config(
        'EINV_QR_SAVE_DIR_OIL', default=rf'{_EINV_QR_ROOT}\OIL_ATTACHMENTS\Bitmap'),
    HANA_BEVERAGE_COMPANY_DB: config(
        'EINV_QR_SAVE_DIR_BEVERAGE', default=rf'{_EINV_QR_ROOT}\BEVERAGE_ATTACHMENTS\Bitmap'),
    HANA_MART_COMPANY_DB: config(
        'EINV_QR_SAVE_DIR_MART', default=rf'{_EINV_QR_ROOT}\MART_ATTACHMENTS\Bitmap'),
}
# Drop unconfigured company DBs (blank key) so lookups can't match by accident.
EINV_QR_SAVE_DIRS = {k: v for k, v in EINV_QR_SAVE_DIRS.items() if k and v}
# Credentials for the share (needed when the Django service account can't reach it
# on its own). Username may be 'user' or 'DOMAIN\\user'. Blank = write as the
# process account (no explicit SMB auth). Requires the `smbprotocol` package.
EINV_QR_SMB_USERNAME = config('EINV_QR_SMB_USERNAME', default='')
EINV_QR_SMB_PASSWORD = config('EINV_QR_SMB_PASSWORD', default='')

# ---------------------------------------------------------------------------
# Payment attachment storage
# ---------------------------------------------------------------------------
# Same shared-folder strategy as EINV_QR_SAVE_DIR above — files are written
# FLAT into these directories under a generated UUID name. No MEDIA_ROOT, no
# year/month/company sub-folders.
#   PAYMENTS_IMAGES=\\JIVO-APP\Payments\Receive_Payments
#   DEPOSIT_PAYMENTS_IMAGES=\\JIVO-APP\Payments\Deposit_Payments
PAYMENTS_IMAGES = config('PAYMENTS_IMAGES', default='')
DEPOSIT_PAYMENTS_IMAGES = config('DEPOSIT_PAYMENTS_IMAGES', default='')
# Credentials for the share, as with EINV_QR_SMB_*. Blank = write as the
# process account with no explicit SMB auth.
PAYMENTS_SMB_USERNAME = config(
    'PAYMENTS_SMB_USERNAME', default=config('EINV_QR_SMB_USERNAME', default=''))
PAYMENTS_SMB_PASSWORD = config(
    'PAYMENTS_SMB_PASSWORD', default=config('EINV_QR_SMB_PASSWORD', default=''))

# Company DBs scanned when looking up an invoice by DocNum (the configured
# HANA_OIL_COMPANY_DB is always tried first). Comma-separated in .env.
EINV_COMPANY_DBS = [d.strip() for d in config(
    'EINV_COMPANY_DBS',
    default='JIVO_OIL_HANADB,JIVO_BEVERAGES_HANADB,JIVO_MART_HANADB,'
            'TEST_OIL_15122025',
).split(',') if d.strip()]

# Non-production (test) company DBs. Generating an IRN from one of these while the
# NIC target is PRODUCTION still works, but produces a real live e-invoice for test
# data — so a loud "cancel it immediately" warning is attached to the result.
EINV_TEST_COMPANY_DBS = [d.strip() for d in config(
    'EINV_TEST_COMPANY_DBS', default='TEST_OIL_15122025',
).split(',') if d.strip()]

# ---- NIC e-Way Bill (standalone system; shares einvoice.crypto) ----
# Defaults reuse the e-Invoice credentials/public key (same PAN); override the
# EWB_* vars in .env only if the e-Way Bill portal issued different ones.
EWB = {
    "BASE_URLS": _split_urls(
        config('EWB_BASE_URLS', default=''),
        'https://ewb1api.gstsandbox.nic.in/ewaybillapi/v1.03,'
        'https://ewb2api.gstsandbox.nic.in/ewaybillapi/v1.03',
    ),
    "AUTH_PATH": config('EWB_AUTH_PATH', default='/Auth'),
    "API_PATH": config('EWB_API_PATH', default='/ewayapi'),
    "CLIENT_ID": config('EWB_CLIENT_ID', default=EINV["CLIENT_ID"]),
    "CLIENT_SECRET": config('EWB_CLIENT_SECRET', default=EINV["CLIENT_SECRET"]),
    "USERNAME": config('EWB_USERNAME', default=EINV["USERNAME"]),
    "PASSWORD": config('EWB_PASSWORD', default=EINV["PASSWORD"]),
    "GSTIN": config('EWB_GSTIN', default=EINV["GSTIN"]),
    "PUBLIC_KEY_PATH": config('EWB_PUBLIC_KEY_PATH', default=EINV["PUBLIC_KEY_PATH"]),
}

# --- Web Push (VAPID) -------------------------------------------------------
# Keys for browser Web Push (Phase 3), loaded from .env via python-decouple
# like the rest of this file. Only the WEB client uses these — React Native /
# Expo push does NOT use VAPID.
#
#   VAPID_PUBLIC_KEY   application server key handed to the browser at
#                      subscribe time (safe to expose; it ships to clients).
#   VAPID_PRIVATE_KEY  raw base64url private key that signs the VAPID JWT.
#                      SECRET — never commit the production value.
#   VAPID_ADMIN_EMAIL  contact address sent to push services (a "mailto:"
#                      prefix is added automatically if you omit it).
#
# The defaults below are DEV-ONLY throwaway keys so the app works out of the
# box locally. Generate a real pair with `python manage.py generate_vapid_keys`
# and set all three in .env for staging/production.
#
# The trailing `or <default>` also covers a .env that has the key present but
# BLANK (e.g. `VAPID_PUBLIC_KEY=`), which python-decouple returns as '' — we
# still fall back to the working dev key rather than a broken empty value.
_DEV_VAPID_PUBLIC_KEY = "BP2Qud4yZDHMSxq31u0i47Dm0MkDeScBDBBbkEoSFvdrYLk3ZRmYXIgZE0sZQuDBRIeNSdpMN5FAzt1DQJyo80Q"
_DEV_VAPID_PRIVATE_KEY = "pCo0fEKbYRCaOCEtlZ4CeH7aQaVx10687SzURg8BUo8"

VAPID_PUBLIC_KEY = config("VAPID_PUBLIC_KEY", default="").strip()
VAPID_PRIVATE_KEY = config("VAPID_PRIVATE_KEY", default="").strip()
VAPID_ADMIN_EMAIL = config("VAPID_ADMIN_EMAIL", default="").strip() or "admin@oms.local"

# A browser subscription is permanently bound to the application server key it
# was created with. So silently falling back to the throwaway dev pair in a real
# deployment POISONS every subscription made while the fallback was active: once
# real keys are set, those rows can never be pushed to again (FCM answers 403,
# WNS answers 401). Only allow the fallback in DEBUG, and refuse to start
# otherwise rather than mint subscriptions against keys we're about to discard.
if not (VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY):
    if DEBUG:
        VAPID_PUBLIC_KEY = VAPID_PUBLIC_KEY or _DEV_VAPID_PUBLIC_KEY
        VAPID_PRIVATE_KEY = VAPID_PRIVATE_KEY or _DEV_VAPID_PRIVATE_KEY
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY must both be set in .env when "
            "DEBUG=False. Generate a pair with `python manage.py generate_vapid_keys`. "
            "Refusing to fall back to the built-in dev keys, which would silently "
            "break Web Push for every browser that subscribes."
        )

# --- Notification framework: registration resolvers (Phase 3.6) -------------
# The generic notification providers resolve a recipient's existing device
# registrations through these configured callables (dotted paths), so the
# framework never imports a business module. The concrete resolvers live in
# orders/notification_resolvers.py and READ (never write) the existing
# push_tokens / web_push_subscriptions tables. Dependency direction stays
# business-module -> notifications; the framework only sees a dotted-path string.
# Override or blank to disable delivery on a given channel.
NOTIFICATION_MOBILE_TOKEN_RESOLVER = config(
    "NOTIFICATION_MOBILE_TOKEN_RESOLVER",
    default="orders.notification_resolvers.resolve_mobile_tokens",
)
NOTIFICATION_WEB_SUBSCRIPTION_RESOLVER = config(
    "NOTIFICATION_WEB_SUBSCRIPTION_RESOLVER",
    default="orders.notification_resolvers.resolve_web_subscriptions",
)

# --- Push token cleanup (scheduled) -----------------------------------------
# `python manage.py prune_push_tokens` deactivates Expo tokens the push service
# reports as dead. It is meant to run nightly from cron / Task Scheduler --
# see docs/push-token-cleanup.md.
#
#   PUSH_TOKEN_CLEANUP_LOG   append-only run log (every run, success or failure)
#   PUSH_TOKEN_CLEANUP_LOCK  lock file that stops two runs overlapping
PUSH_TOKEN_CLEANUP_LOG = config(
    "PUSH_TOKEN_CLEANUP_LOG",
    default=str(BASE_DIR / "logs" / "push_token_cleanup.log"),
)
PUSH_TOKEN_CLEANUP_LOCK = config(
    "PUSH_TOKEN_CLEANUP_LOCK",
    default=str(BASE_DIR / "logs" / "push_token_cleanup.lock"),
)

# `python manage.py prune_web_push_subscriptions` -- the browser Web Push
# equivalent of the Expo token cleanup above. Same nightly cron / Task Scheduler
# model; see docs/web-push-cleanup.md.
WEB_PUSH_CLEANUP_LOG = config(
    "WEB_PUSH_CLEANUP_LOG",
    default=str(BASE_DIR / "logs" / "web_push_cleanup.log"),
)
WEB_PUSH_CLEANUP_LOCK = config(
    "WEB_PUSH_CLEANUP_LOCK",
    default=str(BASE_DIR / "logs" / "web_push_cleanup.lock"),
)

# =========================================================================
# Logging
# =========================================================================
# Until now the project had NO LOGGING configuration at all. Every
# `logger.info(...)` in the codebase went to Django's default handler, which
# for a non-DEBUG process means nowhere — so the structured notification
# delivery lines (`channel=expo outcome=accepted ... duration_ms=...`) could
# not be read in production, and "was this user actually notified?" was
# unanswerable after the fact.
#
# `disable_existing_loggers` is False so that adding this block cannot silence
# any logger that is working today.
#
# Handlers:
#   console      always on; how developers already read output
#   app_file     rotating file for our own code
#   error_file   rotating file for WARNING and above, across everything, so a
#                production problem is one file to open rather than a grep
#
# RotatingFileHandler rather than TimedRotating or logrotate: this deploys on
# Windows Server under Task Scheduler, where logrotate does not exist and a
# size cap is the only thing that reliably bounds disk use.
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

# Level for our own apps. DEBUG locally, INFO on a server, tunable per
# environment without a code change.
APP_LOG_LEVEL = config("APP_LOG_LEVEL", default="DEBUG" if DEBUG else "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        # Structured-ish and greppable. The notification code already emits
        # `key=value` pairs in the message itself, so the prefix only has to
        # supply time, level and origin.
        "standard": {
            "format": "{asctime} {levelname:<8} {name}: {message}",
            "style": "{",
        },
        "console": {
            "format": "{levelname:<8} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "oms.log"),
            "maxBytes": 10 * 1024 * 1024,   # 10 MB
            "backupCount": 5,               # ~50 MB ceiling
            "encoding": "utf-8",
            "formatter": "standard",
        },
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "oms_errors.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "level": "WARNING",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console", "error_file"],
        "level": "WARNING",
    },
    "loggers": {
        # Our own apps. propagate=False so a record is not written twice
        # (once here, once by root).
        app: {
            "handlers": ["console", "app_file", "error_file"],
            "level": APP_LOG_LEVEL,
            "propagate": False,
        }
        for app in (
            "orders", "payments", "approvals", "attachments", "core",
            "devices", "einvoice", "ewaybill", "hana", "invoice", "legal",
            "sap_sync", "serviceLayer", "tracker", "uilabels", "users",
        )
    },
}

# django.request logs a full traceback for every 5xx; keep it, but only in the
# error file so the app log stays readable.
LOGGING["loggers"]["django.request"] = {
    "handlers": ["console", "error_file"],
    "level": "ERROR",
    "propagate": False,
}
