"""
Django settings for OMS project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config    


def _parse_bool(value, default=False):
    if value is None:
        return default
    if isinstance(value, bool):
        return value

    normalized = str(value).strip().lower()
    if normalized in {'1', 'true', 'yes', 'on'}:
        return True
    if normalized in {'0', 'false', 'no', 'off', '', 'release'}:
        return False
    return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# SECRET_KEY = config('SECRET_KEY')
DEBUG = _parse_bool(config('DEBUG', default='false'), default=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#im8s6vmxe)=%xl8$ybjl*fu9(+2=5cf^8$=ok8%bx%0f&^t05'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['103.89.45.75', '127.0.0.1', '10.0.2.2', 'localhost', '192.168.1.240']

# ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    # 'rest_framework.authtoken',
    # 'rest_framework.authto
    'corsheaders',
    'django_apscheduler',
    # Local apps
    'users',
    'orders',
    'sap_sync',
    'hana',
    'SKU',
    'serviceLayer',
    # NIC e-Invoice (IRN) + e-Way Bill (ported from the standalone IRN project)
    'einvoice',
    'ewaybill',
    'invoice',
    'legal',
    'audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditMiddleware',
]

ROOT_URLCONF = 'OMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    },
    'hana': {
        'ENGINE': 'django.db.backends.dummy', 
        'HOST': config('HANA_DB_HOST'),
        'PORT': config('HANA_DB_PORT'),
        'SCHEMA': config('HANA_DB_NAME'),
        'USER': config('HANA_DB_USER'),
        'PASSWORD': config('HANA_DB_PASSWORD'),
    }
    
    
}

#HAND credentials
HANA_SERVICE_LAYER_URL = HANA_SERVICE_LAYER_URL = config('HANA_SERVICE_LAYER_URL')
HANA_USERNAME = config('HANA_USERNAME')
HANA_PASSWORD = config('HANA_PASSWORD')
HANA_COMPANY_DB = config('HANA_COMPANY_DB')
HANA_COMPANY_DB_BEVERAGES = config('HANA_COMPANY_DB_BEVERAGES', default='')
HANA_WAREHOUSE_CODE = config('HANA_WAREHOUSE_CODE', default='GP-FG')
HANA_WAREHOUSE_CODE_BEVERAGES = config('HANA_WAREHOUSE_CODE_BEVERAGES', default='')
# In DEBUG, default to False for local/self-signed SAP endpoints unless explicitly set.
HANA_SSL_VERIFY = config('HANA_SSL_VERIFY', default=not DEBUG, cast=bool)
HANA_SSL_CA_BUNDLE = config('HANA_SSL_CA_BUNDLE', default='')
HANA_CONNECT_TIMEOUT = config('HANA_CONNECT_TIMEOUT', default=15, cast=int)
HANA_READ_TIMEOUT = config('HANA_READ_TIMEOUT', default=120, cast=int)

# SAP SQL Server (source for sync)
SAP_DB_HOST = config('SAP_DB_HOST', default='103.89.45.75')
SAP_DB_PORT = config('SAP_DB_PORT', default=1433, cast=int)
SAP_DB_NAME = config('SAP_DB_NAME', default='Jivo_All_Branches_Live')
SAP_DB_USER = config('SAP_DB_USER', default='ab')
SAP_DB_PASSWORD = config('SAP_DB_PASSWORD', default='Jivo@!@#$')


SAP_APPROVER_USER = config('SAP_APPROVER_USER')
SAP_APPROVER_PASSWORD = config('SAP_APPROVER_PASSWORD') 


# SAP_DRAFTER = 
# SAP_DRAFTER_PASS = 
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'users.User'

# Existing tables use 32-bit integer primary keys, so keep AutoField as the
# project-wide default (this also silences models.W042). Apps that need 64-bit
# ids (e.g. einvoice) opt in via default_auto_field = BigAutoField in apps.py.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Tells WhiteNoise to compress and aggressively cache your static files
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

CORS_ALLOW_ALL_ORIGINS = True


# =========================================================================
# NIC e-Invoice (IRN) + e-Way Bill configuration
# Ported from the standalone IRN project. The einvoice/ewaybill apps read
# these two dicts off `settings`. Values come from .env (python-decouple).
#
# Sandbox (test) and production credentials both live in .env under the same
# variable names — comment/uncomment the appropriate block per server. So
# switching environments is a .env edit only; no code or setting changes here.
#
# The session AuthToken + SEK are cached in Django's default (LocMemCache)
# cache; switch CACHES to Redis for multi-process/Gunicorn deployments.
# =========================================================================
def _split_urls(raw, fallback=''):
    return [u.strip().rstrip('/') for u in (raw or fallback).split(',') if u.strip()]


# ---- NIC e-Invoice ----
EINV = {
    "BASE_URL": config('EINV_BASE_URL', default='https://einv1api.gstsandbox.nic.in'),
    # Failover hosts (NIC runs a load-balanced pair); comma-separated in .env.
    "BASE_URLS": _split_urls(
        config('EINV_BASE_URLS', default=''),
        'https://einv1api.gstsandbox.nic.in,https://einv2api.gstsandbox.nic.in',
    ),
    "AUTH_PATH": config('EINV_AUTH_PATH', default='/eivital/v1.04/auth'),
    "IRN_PATH": config('EINV_IRN_PATH', default='/eicore/v1.03/Invoice'),
    "CANCEL_PATH": config('EINV_CANCEL_PATH', default='/eicore/v1.03/Invoice/Cancel'),
    "MASTER_GSTIN_PATH": config('EINV_MASTER_GSTIN_PATH', default='/eivital/v1.04/Master/gstin'),
    "SYNC_GSTIN_PATH": config('EINV_SYNC_GSTIN_PATH', default='/eivital/v1.04/Master/syncgstin'),
    "EWB_PATH": config('EINV_EWB_PATH', default='/eiewb/v1.03/ewaybill'),
    "HEARTBEAT_PATH": config('EINV_HEARTBEAT_PATH', default='/eivital/v1.04/heartbeat/ping'),
    "CLIENT_ID": config('EINV_CLIENT_ID', default=''),
    "CLIENT_SECRET": config('EINV_CLIENT_SECRET', default=''),
    "USERNAME": config('EINV_USERNAME', default=''),
    "PASSWORD": config('EINV_PASSWORD', default=''),
    "GSTIN": config('EINV_GSTIN', default=''),
    "PUBLIC_KEY_PATH": config(
        'EINV_PUBLIC_KEY_PATH',
        default=str(BASE_DIR / 'secrets' / 'PublicKey' / 'einv_sandbox.pem'),
    ),
}

# When true, creating a real invoice (serviceLayer.SAPInvoiceCreateView, type=INVOICE)
# fires automatic IRN generation for that DocEntry in the background. Every attempt
# is recorded in einvoice_irn_generation_log. Off by default — enable in .env.
EINV_AUTO_GENERATE = _parse_bool(config('EINV_AUTO_GENERATE', default='false'), default=False)

# After a successful IRN generation:
#  - EINV_MIRROR_HANA: also write the record (incl. QR PNG) into the HANA table
#    EINVOICE_IRN (run `manage.py setup_hana_irn_table` once per schema first).
#  - EINV_SAP_WRITEBACK: PATCH the IRN back onto the SAP invoice's e-Billing
#    protocol so SAP shows it as e-invoiced (validate on sandbox first).
# Both off by default and best-effort (never break IRN generation).
EINV_MIRROR_HANA = _parse_bool(config('EINV_MIRROR_HANA', default='false'), default=False)
EINV_SAP_WRITEBACK = _parse_bool(config('EINV_SAP_WRITEBACK', default='false'), default=False)

# Company DBs scanned when looking up an invoice by DocNum (the configured
# HANA_COMPANY_DB is always tried first). Comma-separated in .env.
EINV_COMPANY_DBS = [d.strip() for d in config(
    'EINV_COMPANY_DBS',
    default='JIVO_OIL_HANADB,JIVO_BEVERAGES_HANADB,TEST_OIL_15122025',
).split(',') if d.strip()]

# Non-production (test) company DBs. Generating an IRN from one of these while the
# NIC target is PRODUCTION still works, but produces a real live e-invoice for test
# data — so a loud "cancel it immediately" warning is attached to the result.
EINV_TEST_COMPANY_DBS = [d.strip() for d in config(
    'EINV_TEST_COMPANY_DBS', default='TEST_OIL_15122025',
).split(',') if d.strip()]

# ---- NIC e-Way Bill (standalone system; shares einvoice.crypto) ----
# Defaults reuse the e-Invoice credentials/public key (same PAN); override the
# EWB_* vars in .env only if the e-Way Bill portal issued different ones.
EWB = {
    "BASE_URLS": _split_urls(
        config('EWB_BASE_URLS', default=''),
        'https://ewb1api.gstsandbox.nic.in/ewaybillapi/v1.03,'
        'https://ewb2api.gstsandbox.nic.in/ewaybillapi/v1.03',
    ),
    "AUTH_PATH": config('EWB_AUTH_PATH', default='/Auth'),
    "API_PATH": config('EWB_API_PATH', default='/ewayapi'),
    "CLIENT_ID": config('EWB_CLIENT_ID', default=EINV["CLIENT_ID"]),
    "CLIENT_SECRET": config('EWB_CLIENT_SECRET', default=EINV["CLIENT_SECRET"]),
    "USERNAME": config('EWB_USERNAME', default=EINV["USERNAME"]),
    "PASSWORD": config('EWB_PASSWORD', default=EINV["PASSWORD"]),
    "GSTIN": config('EWB_GSTIN', default=EINV["GSTIN"]),
    "PUBLIC_KEY_PATH": config('EWB_PUBLIC_KEY_PATH', default=EINV["PUBLIC_KEY_PATH"]),
}
