# Generated by Django 5.2.10 on 2026-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UILabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text="Stable machine key used by clients, e.g. 'price_list'. Never edited after creation.", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="The text shown to end users, e.g. 'Distributor Price'.", max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UI Label',
                'verbose_name_plural': 'UI Labels',
                'db_table': 'uilabels_uilabel',
                'ordering': ['field_key'],
            },
        ),
    ]
