# Generated by Django 5.2.10 on 2026-08-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uilabels', '0002_seed_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='uilabel',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Field-only: clients hide the field when this is off.'),
        ),
        migrations.AddField(
            model_name='uilabel',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Field-only: clients make the field mandatory when this is on.'),
        ),
    ]
