# Generated by Django 5.2.10 on 2026-10-01 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=20)),
                ('month', models.CharField(blank=True, max_length=7)),
                ('scope', models.CharField(default='BOTH', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgingDueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50, unique=True)),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgingRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('row_key', models.CharField(max_length=80)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['card_code'], name='cp_realise__card_co_594808_idx')],
                'unique_together': {('card_code', 'row_key')},
            },
        ),
        migrations.CreateModel(
            name='AgingRemarkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50)),
                ('row_key', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['card_code', 'row_key'], name='cp_realise__card_co_33a2a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClosingRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=50, unique=True)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lock_until', models.DateField()),
                ('days', models.PositiveIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('main_group', 'Main Group'), ('state', 'State'), ('person', 'Person'), ('premium_item', 'Premium Items'), ('commodity_item', 'Commodity Items')], max_length=20)),
                ('segment_value', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_realise_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['segment_type', 'segment_value'],
                'indexes': [models.Index(fields=['segment_type', 'year', 'month'], name='cp_realise__segment_1178fe_idx')],
                'unique_together': {('segment_type', 'segment_value', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TargetNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_group', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('segment', models.CharField(blank=True, default='', max_length=20)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_realise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['main_group', 'state', 'sales_person'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_realise__year_07bfb4_idx')],
                'unique_together': {('main_group', 'state', 'sales_person', 'segment', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CityOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=120)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name', 'city'],
                'indexes': [models.Index(fields=['channel', 'state_name'], name='cp_realise__channel_b01719_idx')],
                'unique_together': {('channel', 'state_name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_date', models.DateField()),
                ('claim_month', models.CharField(blank=True, default='', max_length=7)),
                ('party_code', models.CharField(blank=True, default='', max_length=50)),
                ('party_name', models.CharField(max_length=200)),
                ('main_group', models.CharField(blank=True, default='', max_length=100)),
                ('product', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=200)),
                ('claim_type', models.CharField(blank=True, default='', max_length=120)),
                ('ref_inv_no', models.CharField(blank=True, default='', max_length=100)),
                ('coop_no', models.CharField(blank=True, default='', max_length=100)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('claim_pass_date', models.DateField(blank=True, null=True)),
                ('claim_hold', models.CharField(blank=True, default='', max_length=10)),
                ('claim_passed', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('hold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reason_of_hold', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claim_date', '-id'],
                'indexes': [models.Index(fields=['claim_date'], name='cp_realise__claim_d_f5fc2d_idx'), models.Index(fields=['party_code'], name='cp_realise__party_c_e3d105_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditLockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(max_length=160)),
                ('card_code', models.CharField(max_length=50)),
                ('outstanding', models.FloatField(default=0.0)),
                ('required_limit', models.FloatField(default=0.0)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cp_realise.creditlock')),
            ],
            options={
                'indexes': [models.Index(fields=['lock', 'row_key'], name='cp_realise__lock_id_4cdccc_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sub_group', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('tgt_ltrs', models.FloatField(default=0)),
                ('tgt_rate', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realise_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'product_type', 'sub_group'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_realise__year_147fa9_idx'), models.Index(fields=['product_type', 'sub_group'], name='cp_realise__product_bd98f7_idx')],
                'unique_together': {('product_type', 'sub_group', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TargetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_person', models.CharField(blank=True, max_length=100, null=True)),
                ('target_ltrs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('main_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp_realise.maingroupmaster')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cp_realise.statemaster')),
            ],
            options={
                'ordering': ['-year', '-month', 'main_group__name', 'state__name', 'sales_person'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_realise__year_c5de87_idx'), models.Index(fields=['main_group'], name='cp_realise__main_gr_8fe1e2_idx')],
                'unique_together': {('main_group', 'state', 'sales_person', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TerritoryItemTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sub_group', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('retailer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('box_litres', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pcs_per_box', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ss_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dm_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('disc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('target_realise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_item_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name', 'product_type', 'sub_group', 'item_code'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_realise__year_f22532_idx'), models.Index(fields=['channel', 'state_name'], name='cp_realise__channel_88caf3_idx'), models.Index(fields=['item_code'], name='cp_realise__item_co_807925_idx')],
                'unique_together': {('channel', 'state_name', 'item_code', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TerritoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_code', models.CharField(blank=True, default='', max_length=10)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name'],
                'indexes': [models.Index(fields=['channel'], name='cp_realise__channel_1fd3a6_idx')],
                'unique_together': {('channel', 'state_name')},
            },
        ),
        migrations.CreateModel(
            name='TerritoryProductTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('state_name', models.CharField(blank=True, default='', max_length=100)),
                ('sales_person', models.CharField(blank=True, default='', max_length=100)),
                ('product_type', models.CharField(choices=[('PREMIUM', 'Premium'), ('COMMODITY', 'Commodity')], max_length=20)),
                ('sub_group', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_ltrs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('target_realise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territory_product_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['channel', 'state_name', 'product_type', 'sub_group'],
                'indexes': [models.Index(fields=['year', 'month'], name='cp_realise__year_652bbe_idx'), models.Index(fields=['channel', 'state_name'], name='cp_realise__channel_ca0fb2_idx')],
                'unique_together': {('channel', 'state_name', 'product_type', 'sub_group', 'month', 'year')},
            },
        ),
    ]
