# Generated by Django 5.2.10 on 2026-07-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrnGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docentry', models.IntegerField(db_index=True)),
                ('company_db', models.CharField(blank=True, max_length=100, null=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10)),
                ('trigger', models.CharField(choices=[('invoice_create', 'Invoice Created'), ('poll', 'Polling Job'), ('manual', 'Manual'), ('retry', 'Retry')], db_index=True, default='manual', max_length=20)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, max_length=10)),
                ('doc_no', models.CharField(blank=True, max_length=16, null=True)),
                ('irn', models.CharField(blank=True, max_length=64, null=True)),
                ('ack_no', models.CharField(blank=True, max_length=20, null=True)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('irn_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='einvoice.irnrecord')),
            ],
            options={
                'verbose_name': 'IRN Generation Log',
                'db_table': 'einvoice_irn_generation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['docentry', '-created_at'], name='einvoice_ir_docentr_ef95d6_idx'), models.Index(fields=['outcome', '-created_at'], name='einvoice_ir_outcome_67485b_idx')],
            },
        ),
    ]
