# Generated by Django 6.0.3 on 2026-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('item_image', models.ImageField(upload_to='sku_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sku',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
