# Generated by Django 6.0.3 on 2026-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKU', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
