-- Restore the objects the production revert migrations dropped.
--
-- WHY THIS EXISTS
-- ---------------
-- `production` removed HAIS, Combo Mapping and Scheme Engine v2 on 26 Aug 2026
-- and applied four migrations that dropped their tables and columns:
--
--     orders/0058_revert_scheme_v2   orders/0059_revert_combo
--     users/0028_revert_combo        users/0029_drop_hais
--
-- The merge of `test` into `production` restores all three modules, so those
-- four migrations were deleted from the branch. That fixes the code and the
-- migration graph, but it CANNOT fix the live database: the migrations that
-- originally CREATED these objects (orders/0052, orders/0053, orders/0054,
-- users/0026_partyproductassignment_combo_free_item, HAIS/0001_initial) are
-- still recorded as applied in django_migrations, so `migrate` will never
-- re-run them. The rows say the tables exist; the database says otherwise.
--
-- Without this script, `manage.py migrate` on live ABORTS partway through, at
-- orders/0057_scheme_uom_pcs_box_only, which alters `scheme_triggers` and
-- `scheme_benefits` -- tables that are not there.
--
-- WHEN TO RUN
-- -----------
-- Once, on the live database, BEFORE `python manage.py migrate`:
--
--     psql -v ON_ERROR_STOP=1 -d order_management -f scripts/restore_reverted_modules.sql
--
-- (No psql meta-commands are used, so it also runs through any driver.)
--
-- The DDL is taken from `manage.py sqlmigrate` for the creating migrations, so
-- what it builds is exactly what Django's model state expects. Every statement
-- is guarded, so this is idempotent, and a harmless no-op on the test database
-- (10.10.101.117) where the reverts were never applied and the objects are
-- still present and populated.
--
-- It creates EMPTY tables. Nothing is restored into them, because there is
-- nothing to restore: the reverts dropped them while they held no rows on live.

BEGIN;

SET search_path = public;

-- ---------------------------------------------------------------------------
-- 1. Combo companion columns on order_items  (orders/0052, orders/0055)
-- ---------------------------------------------------------------------------
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS is_auto_free boolean NOT NULL DEFAULT false;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS combo_source_code varchar(50) NULL;
ALTER TABLE order_items ALTER COLUMN combo_source_code DROP NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. Combo mapping on party_product_assignments
--    (users/0026_partyproductassignment_combo_free_item)
--
-- `parent_item_code` is NOT added here: it comes from users/0030, which is
-- unapplied on live and runs normally.
-- ---------------------------------------------------------------------------
ALTER TABLE party_product_assignments ADD COLUMN IF NOT EXISTS free_item_code varchar(50) NULL;
ALTER TABLE party_product_assignments ADD COLUMN IF NOT EXISTS free_qty_per_unit numeric(10, 2) NULL;
CREATE INDEX IF NOT EXISTS "party_product_assignments_free_item_code_601887d8"
    ON party_product_assignments (free_item_code);
CREATE INDEX IF NOT EXISTS "party_product_assignments_free_item_code_601887d8_like"
    ON party_product_assignments (free_item_code varchar_pattern_ops);

-- ---------------------------------------------------------------------------
-- 3. Scheme engine v2  (orders/0053_scheme_engine_v2, orders/0054_scheme_category)
--
-- `category` is folded into the CREATE TABLE rather than added afterwards --
-- 0054 exists only because it came later in time, not because the column has
-- to arrive second.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "schemes" (
    "id"            integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "code"          varchar(50) NOT NULL UNIQUE,
    "name"          varchar(255) NOT NULL,
    "description"   text NOT NULL,
    "valid_from"    date NULL,
    "valid_to"      date NULL,
    "is_active"     boolean NOT NULL,
    "priority"      integer NOT NULL,
    "stackable"     boolean NOT NULL,
    "created_at"    timestamp with time zone NOT NULL,
    "updated_at"    timestamp with time zone NOT NULL,
    -- integer, NOT bigint: users_user.id is a plain AutoField. `sqlmigrate`
    -- renders this column as bigint from the historical migration state, but
    -- the live, test and model-derived types are all integer.
    "created_by_id" integer NULL,
    "category"      varchar(20) NOT NULL DEFAULT ''
);
ALTER TABLE "schemes" ALTER COLUMN "category" DROP DEFAULT;

CREATE TABLE IF NOT EXISTS "scheme_benefits" (
    "id"             integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "free_item_code" varchar(50) NULL,
    "free_uom"       varchar(10) NOT NULL,
    "per_qty"        numeric(12, 4) NOT NULL,
    "free_qty"       numeric(12, 4) NOT NULL,
    "max_free_qty"   numeric(12, 4) NULL,
    "scheme_id"      integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "scheme_triggers" (
    "id"          integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "match_type"  varchar(20) NOT NULL,
    "match_value" varchar(100) NOT NULL,
    "min_qty"     numeric(12, 4) NOT NULL,
    "min_uom"     varchar(10) NOT NULL,
    "applies_to"  varchar(20) NOT NULL,
    "scheme_id"   integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "scheme_assignments" (
    "id"            integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "scope_type"    varchar(20) NOT NULL,
    "scope_value"   varchar(100) NOT NULL,
    "category"      varchar(20) NOT NULL,
    "is_exclusion"  boolean NOT NULL,
    "valid_from"    date NULL,
    "valid_to"      date NULL,
    "is_active"     boolean NOT NULL,
    "created_at"    timestamp with time zone NOT NULL,
    "created_by_id" integer NULL,   -- see the note on schemes.created_by_id
    "scheme_id"     integer NOT NULL
);

-- Scheme v2 columns on order_item_schemes.
--
-- benefit_uom / benefit_qty are deliberately absent: they arrive with
-- orders/0058_scheme_benefit_uom_snapshot, which is unapplied on live and runs
-- normally once the tables above exist.
ALTER TABLE "order_item_schemes" ADD COLUMN IF NOT EXISTS "benefit_item_code"  varchar(50) NULL;
ALTER TABLE "order_item_schemes" ADD COLUMN IF NOT EXISTS "computed_qty"       numeric(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE "order_item_schemes" ADD COLUMN IF NOT EXISTS "is_manual_override" boolean NOT NULL DEFAULT false;
ALTER TABLE "order_item_schemes" ADD COLUMN IF NOT EXISTS "scope_type"         varchar(20) NOT NULL DEFAULT '';
ALTER TABLE "order_item_schemes" ADD COLUMN IF NOT EXISTS "scope_value"        varchar(100) NOT NULL DEFAULT '';
ALTER TABLE "order_item_schemes" ADD COLUMN IF NOT EXISTS "scheme_v2_id"       integer NULL;
ALTER TABLE "order_item_schemes" ADD COLUMN IF NOT EXISTS "benefit_id"         integer NULL;
ALTER TABLE "order_item_schemes" ALTER COLUMN "computed_qty"       DROP DEFAULT;
ALTER TABLE "order_item_schemes" ALTER COLUMN "is_manual_override" DROP DEFAULT;
ALTER TABLE "order_item_schemes" ALTER COLUMN "scope_type"         DROP DEFAULT;
ALTER TABLE "order_item_schemes" ALTER COLUMN "scope_value"        DROP DEFAULT;

-- Foreign keys and unique constraints. ADD CONSTRAINT has no IF NOT EXISTS, so
-- each is guarded on pg_constraint by the exact name Django generated.
DO $restore$
DECLARE
    c record;
BEGIN
    FOR c IN
        SELECT * FROM (VALUES
            ('schemes',
             'schemes_created_by_id_3facd9e5_fk_users_user_id',
             'FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('scheme_benefits',
             'scheme_benefits_scheme_id_88fc7cd7_fk_schemes_id',
             'FOREIGN KEY ("scheme_id") REFERENCES "schemes" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('scheme_triggers',
             'scheme_triggers_scheme_id_9d21d6fe_fk_schemes_id',
             'FOREIGN KEY ("scheme_id") REFERENCES "schemes" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('scheme_assignments',
             'scheme_assignments_scheme_id_37ff4f0c_fk_schemes_id',
             'FOREIGN KEY ("scheme_id") REFERENCES "schemes" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('scheme_assignments',
             'scheme_assignments_created_by_id_c9d9ef4f_fk_users_user_id',
             'FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('scheme_assignments',
             'scheme_assignments_scheme_id_scope_type_sco_2a951207_uniq',
             'UNIQUE ("scheme_id", "scope_type", "scope_value", "category")'),
            ('order_item_schemes',
             'order_item_schemes_scheme_v2_id_23ccf535_fk_schemes_id',
             'FOREIGN KEY ("scheme_v2_id") REFERENCES "schemes" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('order_item_schemes',
             'order_item_schemes_benefit_id_44af6170_fk_scheme_benefits_id',
             'FOREIGN KEY ("benefit_id") REFERENCES "scheme_benefits" ("id") DEFERRABLE INITIALLY DEFERRED')
        ) AS t(tbl, conname, definition)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = c.conname) THEN
            EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I %s', c.tbl, c.conname, c.definition);
        END IF;
    END LOOP;
END
$restore$;

CREATE INDEX IF NOT EXISTS "scheme_active_window_idx"        ON "schemes" ("is_active", "valid_from", "valid_to");
CREATE INDEX IF NOT EXISTS "schemes_code_ded6bc53_like"      ON "schemes" ("code" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "schemes_created_by_id_3facd9e5"  ON "schemes" ("created_by_id");
CREATE INDEX IF NOT EXISTS "schemes_category_6e8c99c1"       ON "schemes" ("category");
CREATE INDEX IF NOT EXISTS "schemes_category_6e8c99c1_like"  ON "schemes" ("category" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "scheme_benefits_free_item_code_5687f0fc"      ON "scheme_benefits" ("free_item_code");
CREATE INDEX IF NOT EXISTS "scheme_benefits_free_item_code_5687f0fc_like" ON "scheme_benefits" ("free_item_code" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "scheme_benefits_scheme_id_88fc7cd7"           ON "scheme_benefits" ("scheme_id");
CREATE INDEX IF NOT EXISTS "scheme_trigger_match_idx"           ON "scheme_triggers" ("match_type", "match_value");
CREATE INDEX IF NOT EXISTS "scheme_triggers_scheme_id_9d21d6fe" ON "scheme_triggers" ("scheme_id");
CREATE INDEX IF NOT EXISTS "scheme_assign_scope_idx"                   ON "scheme_assignments" ("scope_type", "scope_value", "is_active");
CREATE INDEX IF NOT EXISTS "scheme_assignments_created_by_id_c9d9ef4f"  ON "scheme_assignments" ("created_by_id");
CREATE INDEX IF NOT EXISTS "scheme_assignments_scheme_id_37ff4f0c"      ON "scheme_assignments" ("scheme_id");
CREATE INDEX IF NOT EXISTS "order_item_schemes_scheme_v2_id_23ccf535"   ON "order_item_schemes" ("scheme_v2_id");
CREATE INDEX IF NOT EXISTS "order_item_schemes_benefit_id_44af6170"     ON "order_item_schemes" ("benefit_id");

-- ---------------------------------------------------------------------------
-- 4. HAIS  (HAIS/0001_initial)
--
-- users/0029_drop_hais ran `DROP SCHEMA hais CASCADE`. It left the `hais` role
-- in place but deactivated, because a user still held it -- reactivating that
-- role is step 5 below, and is deliberately separate.
-- ---------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS hais;

CREATE TABLE IF NOT EXISTS "hais"."tbl_AssetType" (
    "id"         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name"       varchar(100) NOT NULL UNIQUE,
    "sort_order" smallint NOT NULL CHECK ("sort_order" >= 0),
    "is_active"  boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "id_prefix"  varchar(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS "hais"."tbl_Departments" (
    "id"         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name"       varchar(100) NOT NULL UNIQUE,
    "sort_order" smallint NOT NULL CHECK ("sort_order" >= 0),
    "is_active"  boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "hais"."tbl_StorageType" (
    "id"         bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name"       varchar(100) NOT NULL UNIQUE,
    "sort_order" smallint NOT NULL CHECK ("sort_order" >= 0),
    "is_active"  boolean NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS "hais"."tbl_Asset" (
    "asset_id"             varchar(40) NOT NULL PRIMARY KEY,
    "serial_num"           varchar(120) NOT NULL UNIQUE,
    "qr_code"              varchar(160) NOT NULL,
    "company"              varchar(100) NOT NULL,
    "model_num"            varchar(100) NOT NULL,
    "warranty_ends"        varchar(20) NOT NULL,
    "processor"            varchar(120) NOT NULL,
    "memory"               varchar(60) NOT NULL,
    "operating_system"     varchar(80) NOT NULL,
    "storage"              varchar(60) NOT NULL,
    "current_user_id"      varchar(40) NOT NULL,
    "current_user_name"    varchar(120) NOT NULL,
    "prev_user_id"         varchar(40) NOT NULL,
    "prev_user_name"       varchar(120) NOT NULL,
    "email_id"             varchar(120) NOT NULL,
    "current_location"     varchar(160) NOT NULL,
    "handover_date"        varchar(20) NOT NULL,
    "purchase_invoice_no"  varchar(60) NOT NULL,
    "purchase_invoice_date" varchar(20) NOT NULL,
    "amount"               numeric(12, 2) NULL,
    "vendor"               varchar(120) NOT NULL,
    "date_of_last_service" varchar(20) NOT NULL,
    "working_status"       varchar(20) NOT NULL,
    "remarks"              text NOT NULL,
    "created_at"           timestamp with time zone NOT NULL,
    "updated_at"           timestamp with time zone NOT NULL,
    "asset_type_id"        bigint NULL,
    "department_id"        bigint NULL
);

CREATE TABLE IF NOT EXISTS "hais"."tbl_AssetStorageType" (
    "id"              bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "asset_id"        varchar(40) NOT NULL,
    "storage_type_id" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "hais"."tbl_AssetLog" (
    "id"             bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "action"         varchar(40) NOT NULL,
    "event_date"     varchar(20) NOT NULL,
    "from_user_id"   varchar(40) NOT NULL,
    "from_user_name" varchar(120) NOT NULL,
    "to_user_id"     varchar(40) NOT NULL,
    "to_user_name"   varchar(120) NOT NULL,
    "location"       varchar(160) NOT NULL,
    "reason"         varchar(255) NOT NULL,
    "config_json"    jsonb NOT NULL,
    "config_change"  varchar(255) NOT NULL,
    "created_at"     timestamp with time zone NOT NULL,
    "created_by"     varchar(120) NOT NULL,
    "asset_id"       varchar(40) NOT NULL,
    "department_id"  bigint NULL
);

DO $restore_hais$
DECLARE
    c record;
BEGIN
    FOR c IN
        SELECT * FROM (VALUES
            ('tbl_AssetStorageType',
             'hais_asset_storagetype_uq',
             'UNIQUE ("asset_id", "storage_type_id")'),
            ('tbl_Asset',
             'tbl_Asset_asset_type_id_b5bc3242_fk_tbl_AssetType_id',
             'FOREIGN KEY ("asset_type_id") REFERENCES "hais"."tbl_AssetType" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('tbl_Asset',
             'tbl_Asset_department_id_293264a5_fk_tbl_Departments_id',
             'FOREIGN KEY ("department_id") REFERENCES "hais"."tbl_Departments" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('tbl_AssetStorageType',
             'tbl_AssetStorageType_asset_id_07ae446b_fk_tbl_Asset_asset_id',
             'FOREIGN KEY ("asset_id") REFERENCES "hais"."tbl_Asset" ("asset_id") DEFERRABLE INITIALLY DEFERRED'),
            ('tbl_AssetStorageType',
             'tbl_AssetStorageType_storage_type_id_92faadce_fk_tbl_Stora',
             'FOREIGN KEY ("storage_type_id") REFERENCES "hais"."tbl_StorageType" ("id") DEFERRABLE INITIALLY DEFERRED'),
            ('tbl_AssetLog',
             'tbl_AssetLog_asset_id_ef9b243c_fk_tbl_Asset_asset_id',
             'FOREIGN KEY ("asset_id") REFERENCES "hais"."tbl_Asset" ("asset_id") DEFERRABLE INITIALLY DEFERRED'),
            ('tbl_AssetLog',
             'tbl_AssetLog_department_id_88af7288_fk_tbl_Departments_id',
             'FOREIGN KEY ("department_id") REFERENCES "hais"."tbl_Departments" ("id") DEFERRABLE INITIALLY DEFERRED')
        ) AS t(tbl, conname, definition)
    LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = c.conname) THEN
            EXECUTE format('ALTER TABLE %I.%I ADD CONSTRAINT %I %s', 'hais', c.tbl, c.conname, c.definition);
        END IF;
    END LOOP;
END
$restore_hais$;

CREATE INDEX IF NOT EXISTS "hais_asset_serial_idx"  ON "hais"."tbl_Asset" ("serial_num");
CREATE INDEX IF NOT EXISTS "hais_asset_curuser_idx" ON "hais"."tbl_Asset" ("current_user_id");
CREATE INDEX IF NOT EXISTS "hais_asset_status_idx"  ON "hais"."tbl_Asset" ("working_status");
CREATE INDEX IF NOT EXISTS "tbl_AssetType_name_27bc6ba6_like"   ON "hais"."tbl_AssetType" ("name" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "tbl_Departments_name_587ee4a8_like" ON "hais"."tbl_Departments" ("name" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "tbl_StorageType_name_0dc810db_like" ON "hais"."tbl_StorageType" ("name" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "tbl_Asset_asset_id_4d70a2bb_like"   ON "hais"."tbl_Asset" ("asset_id" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "tbl_Asset_serial_num_641d0120_like" ON "hais"."tbl_Asset" ("serial_num" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "tbl_Asset_asset_type_id_b5bc3242"   ON "hais"."tbl_Asset" ("asset_type_id");
CREATE INDEX IF NOT EXISTS "tbl_Asset_department_id_293264a5"   ON "hais"."tbl_Asset" ("department_id");
CREATE INDEX IF NOT EXISTS "tbl_AssetStorageType_asset_id_07ae446b"        ON "hais"."tbl_AssetStorageType" ("asset_id");
CREATE INDEX IF NOT EXISTS "tbl_AssetStorageType_asset_id_07ae446b_like"   ON "hais"."tbl_AssetStorageType" ("asset_id" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "tbl_AssetStorageType_storage_type_id_92faadce" ON "hais"."tbl_AssetStorageType" ("storage_type_id");
CREATE INDEX IF NOT EXISTS "tbl_AssetLog_asset_id_ef9b243c"      ON "hais"."tbl_AssetLog" ("asset_id");
CREATE INDEX IF NOT EXISTS "tbl_AssetLog_asset_id_ef9b243c_like" ON "hais"."tbl_AssetLog" ("asset_id" varchar_pattern_ops);
CREATE INDEX IF NOT EXISTS "tbl_AssetLog_department_id_88af7288" ON "hais"."tbl_AssetLog" ("department_id");
CREATE INDEX IF NOT EXISTS "hais_log_asset_idx" ON "hais"."tbl_AssetLog" ("asset_id", "id");

COMMIT;

-- ---------------------------------------------------------------------------
-- 5. OPTIONAL, and a separate decision: reactivate the `hais` role.
--
-- users/0029_drop_hais deactivated it rather than deleting it, because user
-- 'Sushil' holds it and User.role is on_delete=PROTECT. Nobody can reach the
-- HAIS screens while it is inactive. Run this only if HAIS is meant to be
-- usable again on live.
--
--     UPDATE users_role SET is_active = true WHERE name = 'hais';
-- ---------------------------------------------------------------------------
