"""Write a `.env` that CI can boot from, without committing any secret.

`cp .env.example .env` gets everything except the three values that must never
live in the repository: SECRET_KEY, which signs every JWT, and the VAPID pair,
whose private half authorises push to every browser subscribed to this app.
This script appends freshly generated versions of those three, so each CI run
uses keys that exist only for its own runner and are discarded with it.

Nothing here is reusable as a deployment tool — the keys are thrown away, so a
server built this way could not verify a token it issued after a restart.

    python scripts/write_ci_env.py [--env-file .env]
"""
from __future__ import annotations

import argparse
import base64
import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _b64url(raw: bytes) -> str:
    """Unpadded base64url — the encoding the Web Push spec requires for VAPID
    keys, and what `orders.management.commands.generate_vapid_keys` emits."""
    return base64.urlsafe_b64encode(raw).decode().rstrip('=')


def generate_vapid_pair() -> tuple[str, str]:
    """(public, private), matching generate_vapid_keys byte for byte in format.

    The public key is the uncompressed P-256 point; the private key is the raw
    32-byte scalar. Anything else and the browser rejects the subscription.
    """
    from cryptography.hazmat.primitives import serialization
    from py_vapid import Vapid

    vapid = Vapid()
    vapid.generate_keys()
    public = _b64url(vapid.public_key.public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint,
    ))
    private = _b64url(
        vapid.private_key.private_numbers().private_value.to_bytes(32, 'big'))
    return public, private


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--env-file', default=str(REPO_ROOT / '.env'))
    parser.add_argument(
        '--force', action='store_true',
        help='overwrite an existing .env (refused by default, because on a '
             'developer machine that file holds the real credentials)')
    args = parser.parse_args(argv)

    target = Path(args.env_file)
    if target.exists() and not args.force:
        print(f'refusing to overwrite {target} — pass --force if you mean it',
              file=sys.stderr)
        return 2

    example = REPO_ROOT / '.env.example'
    if not example.exists():
        print(f'{example} is missing', file=sys.stderr)
        return 2

    shutil.copyfile(example, target)

    public, private = generate_vapid_pair()
    secret_key = _b64url(os.urandom(48))

    with target.open('a', encoding='utf-8') as handle:
        handle.write(
            '\n'
            '# --- generated by scripts/write_ci_env.py, valid for this run only\n'
            f'SECRET_KEY={secret_key}\n'
            f'VAPID_PUBLIC_KEY={public}\n'
            f'VAPID_PRIVATE_KEY={private}\n'
        )

    # `.env.example` leaves SECRET_KEY blank; python-decouple takes the LAST
    # assignment, so the appended one wins. Say so, because a duplicated key in
    # a config file normally means a mistake.
    print(f'wrote {target} (SECRET_KEY and VAPID pair appended, overriding the '
          f'blank SECRET_KEY from .env.example)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
