# Generated by Django 5.2.10 on 2026-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'inventory permission',
                'verbose_name_plural': 'inventory permissions',
                'permissions': (('view_inventory', 'Can view inventory dashboard'), ('manage_inventory', 'Can manage inventory dashboard'), ('view_stock_available', 'Can view stock available')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
