# Generated by Django 5.2.10 on 2026-08-04 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # The dedicated Postgres schema must exist before any hais."." table is
        # created. IF NOT EXISTS makes it safe to re-run; the reverse drops it
        # only once every table in it has already been removed by the unwinds
        # above (CASCADE guards against a half-rolled-back state).
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS hais;',
            reverse_sql='DROP SCHEMA IF EXISTS hais CASCADE;',
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_prefix', models.CharField(blank=True, default='', max_length=8)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'db_table': 'hais"."tbl_AssetType',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'db_table': 'hais"."tbl_Departments',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Type',
                'db_table': 'hais"."tbl_StorageType',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('serial_num', models.CharField(max_length=120, unique=True)),
                ('qr_code', models.CharField(blank=True, default='', max_length=160)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('model_num', models.CharField(blank=True, default='', max_length=100)),
                ('warranty_ends', models.CharField(blank=True, default='', max_length=20)),
                ('processor', models.CharField(blank=True, default='', max_length=120)),
                ('memory', models.CharField(blank=True, default='', max_length=60)),
                ('operating_system', models.CharField(blank=True, default='', max_length=80)),
                ('storage', models.CharField(blank=True, default='', max_length=60)),
                ('current_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('current_user_name', models.CharField(blank=True, default='', max_length=120)),
                ('prev_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('prev_user_name', models.CharField(blank=True, default='', max_length=120)),
                ('email_id', models.CharField(blank=True, default='', max_length=120)),
                ('current_location', models.CharField(blank=True, default='', max_length=160)),
                ('handover_date', models.CharField(blank=True, default='', max_length=20)),
                ('purchase_invoice_no', models.CharField(blank=True, default='', max_length=60)),
                ('purchase_invoice_date', models.CharField(blank=True, default='', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, default='', max_length=120)),
                ('date_of_last_service', models.CharField(blank=True, default='', max_length=20)),
                ('working_status', models.CharField(choices=[('Working', 'Working'), ('Under Repair', 'Under Repair'), ('Not Working', 'Not Working'), ('In Stock', 'In Stock'), ('Scrapped', 'Scrapped')], default='Working', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='HAIS.assettype')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='HAIS.department')),
            ],
            options={
                'verbose_name': 'Asset',
                'db_table': 'hais"."tbl_Asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetStorageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_links', to='HAIS.asset')),
                ('storage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='HAIS.storagetype')),
            ],
            options={
                'verbose_name': 'Asset Storage Type',
                'db_table': 'hais"."tbl_AssetStorageType',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='storage_types',
            field=models.ManyToManyField(blank=True, related_name='assets', through='HAIS.AssetStorageType', to='HAIS.storagetype'),
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('event_date', models.CharField(blank=True, default='', max_length=20)),
                ('from_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('from_user_name', models.CharField(blank=True, default='', max_length=120)),
                ('to_user_id', models.CharField(blank=True, default='', max_length=40)),
                ('to_user_name', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('config_change', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='HAIS.asset')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='HAIS.department')),
            ],
            options={
                'verbose_name': 'Asset Log',
                'db_table': 'hais"."tbl_AssetLog',
                'ordering': ['asset_id', 'id'],
                'indexes': [models.Index(fields=['asset', 'id'], name='hais_log_asset_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetstoragetype',
            constraint=models.UniqueConstraint(fields=('asset', 'storage_type'), name='hais_asset_storagetype_uq'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_num'], name='hais_asset_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['current_user_id'], name='hais_asset_curuser_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['working_status'], name='hais_asset_status_idx'),
        ),
    ]
