# Generated by Django 5.2.10 on 2026-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='has_config',
            field=models.BooleanField(default=True),
        ),
    ]
