# Generated by Django 5.2.10 on 2026-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAIS', '0002_assettype_has_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='has_config',
        ),
        migrations.AddField(
            model_name='assettype',
            name='field_config',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
