# Generated by Django 5.2.10 on 2026-09-12 12:04

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ------------------------------------------------------------------
        # Prerequisites, in this order and before any table.
        #
        # 1. The dedicated `workflow` schema must exist before any
        #    workflow"."<table> is created. IF NOT EXISTS makes it re-runnable;
        #    the reverse drops it only once the unwinds above have removed
        #    every table (CASCADE guards a half-rolled-back state). Same
        #    pattern as HAIS/0001 and the payments schema move.
        #
        # 2. btree_gist must be installed before the exclusion constraint on
        #    workflow_user_replacements: that constraint combines an equality
        #    test on a bigint (old_user_id) with an overlap test on a
        #    daterange, and GiST cannot do equality on a bigint without this
        #    extension. CREATE EXTENSION needs superuser/rds_superuser AT
        #    MIGRATE TIME only — never at runtime. It is a database-wide
        #    object, so if another app already installed it this is a no-op.
        # ------------------------------------------------------------------
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS workflow;',
            reverse_sql='DROP SCHEMA IF EXISTS workflow CASCADE;',
        ),
        BtreeGistExtension(),
        migrations.CreateModel(
            name='TestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=50)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
            ],
            options={
                'verbose_name': 'Workflow Test Document',
                'db_table': 'workflow"."workflow_test_document',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company'], name='workflow_testdoc_comp_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('business_table', models.CharField(help_text='Qualified relation the module\'s documents live in, e.g. workflow"."workflow_test_document', max_length=120)),
                ('business_key_column', models.CharField(help_text='Column/attribute a configured query exposes for document identity. Bound as a parameter, never interpolated.', max_length=60)),
                ('flow_table', models.CharField(help_text="Qualified relation holding this module's flow rows.", max_length=120)),
                ('flow_model', models.CharField(blank=True, default='', help_text="Dotted 'app_label.ModelName' of the concrete flow model.", max_length=120)),
            ],
            options={
                'verbose_name': 'Workflow Module',
                'db_table': 'workflow"."workflow_modules',
                'ordering': ['code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('code', models.Func(models.F('code'), function='UPPER'))), name='workflow_module_code_upper')],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_scope', models.CharField(choices=[('ALL', 'All companies'), ('SPECIFIC', 'A specific company')], default='ALL', help_text='ALL applies to every company; SPECIFIC to `company` only.', max_length=8)),
                ('company', models.CharField(blank=True, choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], help_text='NULL when scope is ALL; a company code when SPECIFIC.', max_length=20, null=True)),
                ('code', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflows', to='workflow.workflowmodule')),
            ],
            options={
                'verbose_name': 'Workflow',
                'db_table': 'workflow"."workflows',
                'ordering': ['module__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_scope', models.CharField(choices=[('ALL', 'All companies'), ('SPECIFIC', 'A specific company')], default='ALL', help_text='ALL applies to every company; SPECIFIC to `company` only.', max_length=8)),
                ('company', models.CharField(blank=True, choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], help_text='NULL when scope is ALL; a company code when SPECIFIC.', max_length=20, null=True)),
                ('name', models.CharField(max_length=120)),
                ('query_text', models.TextField()),
                ('type', models.CharField(blank=True, default='', help_text='JSAP parity only — nothing in the engine reads this.', max_length=30)),
                ('key_column', models.CharField(blank=True, default='', help_text="Overrides the module's business_key_column when this query aliases its key differently.", max_length=60)),
                ('validated_at', models.DateTimeField(blank=True, help_text='Set by the validator. NULL means never executed.', null=True)),
                ('validation_error', models.TextField(blank=True, default='')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Query',
                'db_table': 'workflow"."workflow_queries',
                'ordering': ['workflow', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sequence', models.PositiveSmallIntegerField(help_text='1-based stage execution order. Not selection priority.')),
                ('user', models.ForeignKey(help_text='The single configured user for this stage.', on_delete=django.db.models.deletion.PROTECT, related_name='workflow_stages', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Stage',
                'db_table': 'workflow"."workflow_stages',
                'ordering': ['workflow', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.BigIntegerField()),
                ('sequence', models.PositiveIntegerField(help_text='Monotonic per (module, flow_id), across all executions.')),
                ('stage_name', models.CharField(blank=True, default='', max_length=120)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('EXPIRE', 'Expire')], max_length=12)),
                ('acted_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('remarks', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('acted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acted_by', models.ForeignKey(blank=True, help_text='Who actually acted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.ForeignKey(blank=True, help_text='The configured stage user, when a replacement was active.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_actions_on_behalf', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='workflow.workflowmodule')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='workflow.workflowstage')),
            ],
            options={
                'verbose_name': 'Workflow Action',
                'db_table': 'workflow"."workflow_action',
                'ordering': ['module', 'flow_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TestFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('current_sequence', models.PositiveSmallIntegerField(default=1)),
                ('company', models.CharField(blank=True, default='', max_length=20)),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Routing inputs and selection explanation ONLY. Never a copy of the business document.')),
                ('integration_status', models.CharField(default='PENDING', max_length=12)),
                ('lock_version', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flows', to='workflow.testdocument')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflow')),
                ('matched_query', models.ForeignKey(blank=True, help_text='Which configured query selected this workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowquery')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflowstage')),
            ],
            options={
                'verbose_name': 'Workflow Test Flow',
                'db_table': 'workflow"."workflow_test_flow',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_id', models.BigIntegerField(help_text="Row id in the module's own flow table. Intentionally not a FK — the target table varies by module.")),
                ('sequence', models.PositiveSmallIntegerField(help_text='Stage sequence, denormalised so the inbox needs no join.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.workflowmodule')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.workflowstage')),
                ('stage_user', models.ForeignKey(help_text="The stage's CONFIGURED user. Effective actor is resolved by date at read/action time.", on_delete=django.db.models.deletion.PROTECT, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow Task',
                'db_table': 'workflow"."workflow_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowUserReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(help_text='Inclusive.')),
                ('end_date', models.DateField(help_text='Inclusive.')),
                ('new_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_replacing', to=settings.AUTH_USER_MODEL)),
                ('old_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_replaced_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow User Replacement',
                'db_table': 'workflow"."workflow_user_replacements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TestDocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('STAGE_APPROVED', 'Stage approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.testdocument')),
            ],
            options={
                'verbose_name': 'Workflow Test Document Log',
                'db_table': 'workflow"."workflow_test_document_log',
                'ordering': ['document', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('document', 'sequence'), name='workflow_testdoclog_seq_uq')],
            },
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['module'], name='workflow_module_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['module', 'company_scope', 'company'], name='workflow_module_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('module', 'code'), name='workflow_module_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('company_scope__in', ['ALL', 'SPECIFIC'])), name='workflow_company_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', True), ('company__in', ['OIL', 'BEVERAGES', 'MART']), _connector='OR'), name='workflow_company_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('company_scope', 'ALL')), models.Q(('company__isnull', False), ('company_scope', 'SPECIFIC')), _connector='OR'), name='workflow_company_scope_consistent'),
        ),
        migrations.AddIndex(
            model_name='workflowquery',
            index=models.Index(fields=['workflow'], name='workflow_query_wf_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowquery',
            index=models.Index(fields=['workflow', 'company_scope', 'company'], name='workflow_query_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowquery',
            constraint=models.UniqueConstraint(fields=('workflow', 'name'), name='workflow_query_name_uq'),
        ),
        migrations.AddConstraint(
            model_name='workflowquery',
            constraint=models.CheckConstraint(condition=models.Q(('query_text__iregex', '^\\s*(select|with)\\b')), name='workflow_query_select_only'),
        ),
        migrations.AddConstraint(
            model_name='workflowquery',
            constraint=models.CheckConstraint(condition=models.Q(('company_scope__in', ['ALL', 'SPECIFIC'])), name='workflow_query_company_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='workflowquery',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', True), ('company__in', ['OIL', 'BEVERAGES', 'MART']), _connector='OR'), name='workflow_query_company_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='workflowquery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('company_scope', 'ALL')), models.Q(('company__isnull', False), ('company_scope', 'SPECIFIC')), _connector='OR'), name='workflow_query_company_scope_consistent'),
        ),
        migrations.AddIndex(
            model_name='workflowstage',
            index=models.Index(fields=['workflow', 'sequence'], name='workflow_stage_wf_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstage',
            index=models.Index(fields=['user'], name='workflow_stage_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='workflow_stage_seq_uq'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='workflow_stage_seq_positive'),
        ),
        migrations.AddIndex(
            model_name='workflowaction',
            index=models.Index(fields=['module', 'flow_id', 'acted_at'], name='workflow_action_flow_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowaction',
            constraint=models.UniqueConstraint(fields=('module', 'flow_id', 'sequence'), name='workflow_action_sequence_uq'),
        ),
        migrations.AddIndex(
            model_name='testflow',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['status', 'current_stage'], name='workflow_testflow_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='testflow',
            constraint=models.UniqueConstraint(fields=('document',), name='workflow_testflow_document_uq'),
        ),
        migrations.AddConstraint(
            model_name='testflow',
            constraint=models.CheckConstraint(condition=models.Q(('current_sequence__gte', 1)), name='workflow_testflow_seq_positive'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['stage_user', 'status'], name='workflow_task_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtask',
            index=models.Index(fields=['module', 'flow_id'], name='workflow_task_flow_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('module', 'flow_id', 'stage'), name='workflow_task_one_open_per_stage_uq'),
        ),
        migrations.AddIndex(
            model_name='workflowuserreplacement',
            index=models.Index(fields=['old_user', 'start_date', 'end_date'], name='wf_replacement_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowuserreplacement',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='workflow_replacement_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='workflowuserreplacement',
            constraint=models.CheckConstraint(condition=models.Q(('old_user', models.F('new_user')), _negated=True), name='workflow_replacement_not_self'),
        ),
        migrations.AddConstraint(
            model_name='workflowuserreplacement',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('old_user', '='), (models.Func(models.F('start_date'), models.F('end_date'), models.Value('[]'), function='daterange', output_field=django.contrib.postgres.fields.ranges.DateRangeField()), '&&')], name='workflow_replacement_no_overlap'),
        ),
    ]
