# Generated by Django 5.2.10 on 2026-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowquery',
            name='workflow_query_select_only',
        ),
        migrations.AlterField(
            model_name='workflowmodule',
            name='business_table',
            field=models.CharField(help_text='Schema-qualified relation the module\'s documents live in, as written in raw SQL — e.g. "workflow.workflow_test_document". Do NOT use Django\'s db_table quoting form (schema"."table); a configured query is raw SQL and would not parse.', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='workflowquery',
            constraint=models.CheckConstraint(condition=models.Q(('query_text__iregex', '^\\s*(select|with)\\y')), name='workflow_query_select_only'),
        ),
    ]
