# Generated by Django 5.2.10 on 2026-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_fix_select_only_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmodule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive modules are hidden and cannot start workflows. Deactivate rather than delete — history references this row.'),
        ),
    ]
