# Generated by Django 5.2.10 on 2026-09-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_module_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive rows are hidden and take no part in selection. Deactivate rather than delete — history references these.'),
        ),
        migrations.AddField(
            model_name='workflowquery',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive rows are hidden and take no part in selection. Deactivate rather than delete — history references these.'),
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive rows are hidden and take no part in selection. Deactivate rather than delete — history references these.'),
        ),
        migrations.AddField(
            model_name='workflowuserreplacement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive rows are hidden and take no part in selection. Deactivate rather than delete — history references these.'),
        ),
    ]
