"""Drop the engine's runtime tables and the TestFlow harness.

    workflow_task                 -> the module owns its approval runtime
    workflow_action               -> the module owns its approval history
    workflow_test_flow            -> verification harness
    workflow_test_document        -> verification harness
    workflow_test_document_log    -> verification harness

WHY THE RUNTIME TABLES GO
-------------------------
`workflow_task` and `workflow_action` assumed ONE universal shape for every
module's approval runtime and history. A real module's task carries
module-specific columns and its history is part of its own audit story, so
forcing both through an engine-owned table meant every module either bent to
that shape or kept a second copy of its own. The engine now answers "which
workflow applies, and what are its stages?" and the module builds its own
task, action and lifecycle from that.

`WorkflowFlowBase` goes with them for the same reason: it prescribed the flow
row (status, current_stage, current_sequence, lock_version), so the engine was
still dictating the module's runtime even though the table lived in the
module's own schema.

DATA REMOVED (inspected before writing this migration)
------------------------------------------------------
    workflow_task               0 rows
    workflow_action             0 rows
    workflow_test_flow          0 rows
    workflow_test_document      3 rows  — demo fixtures from the (now removed)
                                          seed_workflow_demo command:
                                          DEMO-OIL-9500, DEMO-OIL-1200,
                                          DEMO-BEVERAGES-800
    workflow_test_document_log  0 rows

No business data. The five configuration tables — workflow_modules,
workflows, workflow_queries, workflow_stages, workflow_user_replacements —
are untouched, as is every schema outside `workflow`.

The TESTFLOW registry row and its demo configuration are removed separately
below: they configured the harness this migration deletes, and their condition
queries select from `workflow.workflow_test_document`, which will no longer
exist.
"""
# Generated by Django 5.2.10 on 2026-09-14 09:52

from django.db import migrations


def _remove_testflow_configuration(apps, schema_editor):
    """Delete the TESTFLOW module registration and everything under it.

    Scoped to that one code. A real module's configuration is never touched,
    and if someone has meanwhile registered a genuine module this is a no-op
    for it.
    """
    WorkflowModule = apps.get_model('workflow', 'WorkflowModule')
    Workflow = apps.get_model('workflow', 'Workflow')
    WorkflowQuery = apps.get_model('workflow', 'WorkflowQuery')
    WorkflowStage = apps.get_model('workflow', 'WorkflowStage')

    modules = WorkflowModule.objects.filter(code='TESTFLOW')
    if not modules.exists():
        return
    workflows = Workflow.objects.filter(module__in=modules)
    counts = (workflows.count(),
              WorkflowQuery.objects.filter(workflow__in=workflows).count(),
              WorkflowStage.objects.filter(workflow__in=workflows).count())
    WorkflowQuery.objects.filter(workflow__in=workflows).delete()
    WorkflowStage.objects.filter(workflow__in=workflows).delete()
    workflows.delete()
    modules.delete()
    print(f'  removed TESTFLOW harness configuration: '
          f'{counts[0]} workflows, {counts[1]} queries, {counts[2]} stages')


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_simplify_query_company'),
    ]

    operations = [
        # The harness's own configuration goes with the harness. Its queries
        # read `workflow.workflow_test_document`, so leaving them behind would
        # mean rows that look configured and can never be evaluated.
        migrations.RunPython(_remove_testflow_configuration,
                             migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='testflow',
            name='document',
        ),
        migrations.RemoveField(
            model_name='testdocumentlog',
            name='document',
        ),
        migrations.RemoveField(
            model_name='testdocumentlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testflow',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='testflow',
            name='matched_query',
        ),
        migrations.RemoveField(
            model_name='testflow',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='workflowaction',
            name='acted_by',
        ),
        migrations.RemoveField(
            model_name='workflowaction',
            name='module',
        ),
        migrations.RemoveField(
            model_name='workflowaction',
            name='on_behalf_of',
        ),
        migrations.RemoveField(
            model_name='workflowaction',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='workflowtask',
            name='module',
        ),
        migrations.RemoveField(
            model_name='workflowtask',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='workflowtask',
            name='stage_user',
        ),
        migrations.DeleteModel(
            name='TestDocument',
        ),
        migrations.DeleteModel(
            name='TestDocumentLog',
        ),
        migrations.DeleteModel(
            name='TestFlow',
        ),
        migrations.DeleteModel(
            name='WorkflowAction',
        ),
        migrations.DeleteModel(
            name='WorkflowTask',
        ),
    ]
