# Generated by Django 5.2.10 on 2026-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_drop_runtime_and_testflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="When a document matches several workflows, the lowest priority wins. A tie is still an error.",
            ),
        ),
    ]
