# Generated by Django 5.2.10 on 2026-08-03 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('attachment_type', models.CharField(choices=[('CHEQUE_IMAGE', 'Cheque image'), ('UPI_SCREENSHOT', 'UPI screenshot'), ('DEPOSIT_SLIP', 'Bank deposit slip'), ('DEPOSIT_RECEIPT', 'Deposit receipt')], db_index=True, max_length=20)),
                ('stored_name', models.CharField(max_length=120, unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_attachment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_att_target')],
            },
        ),
    ]
