# Generated by Django 5.2.10 on 2026-09-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='stored_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
