# Generated by Django 6.0.3 on 2026-05-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_merge_20260511_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_foc',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
