# Generated by Django 6.0.3 on 2026-05-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_order_is_foc_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_foc',
            field=models.BooleanField(default=False),
        ),
    ]
