# Generated by Django 5.2.14 on 2026-05-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_alter_categories_id_alter_dispatchlocation_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffproductprice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='staffproductprice',
            table='staff_product_prices',
        ),
    ]
