# Generated by Django 5.2.14 on 2026-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_staffproductprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('PARTY', 'Party'), ('STAFF', 'Staff')], default='PARTY', max_length=20),
        ),
    ]
