# Generated by Django 5.2.14 on 2026-05-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_order_employee_name_order_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='employee_name',
            new_name='employee_id',
        ),
    ]
