# Generated by Django 6.0.3 on 2026-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_orderflowconfig_flow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderflowconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
