# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_categories_id_alter_dispatchlocation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateapproverrule',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rateapproverrule',
            unique_together={('category', 'variety')},
        ),
    ]
