# Generated by Django 6.0.3 on 2026-06-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_orderflowconfig_id'),
        ('orders', '0036_update_rate_approver_rule_unique_key'),
    ]

    operations = [
    ]
