# Generated by Django 6.0.3 on 2026-06-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_productdetails_orderitem_sub_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='sub_group',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='sub_group',
        ),
    ]
