# Generated by Django 6.0.3 on 2026-06-19 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_rateapproverrule_sub_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyOrderFlowConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('rate_approval_enabled', models.BooleanField(default=True)),
                ('billing_enabled', models.BooleanField(default=True)),
                ('auditor_enabled', models.BooleanField(default=True)),
                ('rate_conditions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_party_order_flow_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party Order Flow Config',
                'verbose_name_plural': 'Party Order Flow Config',
                'db_table': 'party_order_flow_config',
            },
        ),
    ]
