# Generated by Django 6.0.3 on 2026-06-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_partyorderflowconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyorderflowconfig',
            name='flow_type',
            field=models.CharField(default='ASM', max_length=20),
        ),
        migrations.AlterField(
            model_name='partyorderflowconfig',
            name='card_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='partyorderflowconfig',
            unique_together={('card_code', 'flow_type')},
        ),
    ]
