# Generated by Django 6.0.3 on 2026-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_partyorderflowconfig_flow_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partyorderflowconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partyorderflowconfig',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='partyorderflowconfig',
            unique_together={('card_code', 'category', 'flow_type')},
        ),
    ]
