# Generated by Django 5.2.10 on 2026-08-08 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_orderitem_auto_free_combo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemscheme',
            name='benefit_item_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitemscheme',
            name='computed_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitemscheme',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitemscheme',
            name='scope_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitemscheme',
            name='scope_value',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('stackable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schemes',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderitemscheme',
            name='scheme_v2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item_schemes', to='orders.scheme'),
        ),
        migrations.CreateModel(
            name='SchemeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('PARTY', 'Party (card code)'), ('MAIN_GROUP', 'Main group'), ('STATE', 'State'), ('CATEGORY', 'Category'), ('ALL', 'All vendors')], default='PARTY', max_length=20)),
                ('scope_value', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('is_exclusion', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheme_assignments', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.scheme')),
            ],
            options={
                'db_table': 'scheme_assignments',
                'ordering': ['scheme_id', 'scope_type', 'scope_value'],
            },
        ),
        migrations.CreateModel(
            name='SchemeBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_item_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('free_uom', models.CharField(choices=[('QTY', 'Qty'), ('PCS', 'Pieces'), ('BOX', 'Boxes'), ('LTR', 'Litres')], default='PCS', max_length=10)),
                ('per_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('free_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('max_free_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='orders.scheme')),
            ],
            options={
                'db_table': 'scheme_benefits',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='orderitemscheme',
            name='benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_schemes', to='orders.schemebenefit'),
        ),
        migrations.CreateModel(
            name='SchemeTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('ITEM', 'Item code'), ('SUB_GROUP', 'Sub group'), ('VARIETY', 'Variety'), ('BRAND', 'Brand'), ('CATEGORY', 'Category'), ('ALL', 'Any item')], default='ITEM', max_length=20)),
                ('match_value', models.CharField(blank=True, default='', max_length=100)),
                ('min_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('min_uom', models.CharField(choices=[('QTY', 'Qty'), ('PCS', 'Pieces'), ('BOX', 'Boxes'), ('LTR', 'Litres')], default='QTY', max_length=10)),
                ('applies_to', models.CharField(choices=[('PAID_LINE', 'Paid line'), ('FREE_LINE', 'Free (combo) line'), ('BOTH', 'Both')], default='PAID_LINE', max_length=20)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='orders.scheme')),
            ],
            options={
                'db_table': 'scheme_triggers',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='scheme',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_to'], name='scheme_active_window_idx'),
        ),
        migrations.AddIndex(
            model_name='schemeassignment',
            index=models.Index(fields=['scope_type', 'scope_value', 'is_active'], name='scheme_assign_scope_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schemeassignment',
            unique_together={('scheme', 'scope_type', 'scope_value', 'category')},
        ),
        migrations.AddIndex(
            model_name='schemetrigger',
            index=models.Index(fields=['match_type', 'match_value'], name='scheme_trigger_match_idx'),
        ),
    ]
