# Generated by Django 5.2.10 on 2026-08-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_scheme_engine_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(blank=True, choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, default='', max_length=20),
        ),
    ]
