# Generated by Django 5.2.10 on 2026-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_fix_combo_source_code_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
