# Generated by Django 5.2.10 on 2026-08-11 10:18
#
# Split into state + database halves on 2026-08-26, when the branch merge brought
# `0052_order_warehouse_code` into the same tree. That migration re-cut this same
# column as a direct child of 0051 so warehouse selection could ship ahead of the
# scheme-engine chain, and it has been applied to databases this one has not
# reached. A plain AddField would emit `ADD COLUMN` there and die with "column
# already exists", so the DDL is guarded instead.
#
# The SQL reproduces exactly what AddField emits (add NOT NULL with a default so
# existing rows fill, then drop the default), leaving the column definition
# identical on a database that gets it from here and one that already had it.
# DROP DEFAULT is a no-op where no default is set.
#
# 0052 now carries no operations, so this is the single migration that adds
# `warehouse_code` to model state.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_fix_combo_source_code_nullable'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='warehouse_code',
                    field=models.CharField(blank=True, default='', max_length=20),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE orders "
                        "ADD COLUMN IF NOT EXISTS warehouse_code varchar(20) "
                        "NOT NULL DEFAULT '';"
                        "ALTER TABLE orders "
                        "ALTER COLUMN warehouse_code DROP DEFAULT;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE orders "
                        "DROP COLUMN IF EXISTS warehouse_code;"
                    ),
                ),
            ],
        ),
    ]
