# Generated by Django 5.2.10 on 2026-08-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_alter_order_order_type'),
        ('orders', '0056_order_warehouse_code'),
    ]

    operations = [
    ]
