# Generated by Django 5.2.10 on 2026-08-22 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0052_order_items_orphan_column_defaults"),
        ("orders", "0056_order_warehouse_code"),
    ]

    operations = []
