# Generated by Django 5.2.10 on 2026-08-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_merge_20260822_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('PARTY', 'Party'), ('STAFF', 'Staff'), ('DISTRIBUTOR', 'Distributor')], default='PARTY', max_length=20),
        ),
    ]
