# Generated by Django 5.2.10 on 2026-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0057_scheme_uom_pcs_box_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemscheme",
            name="benefit_qty",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="orderitemscheme",
            name="benefit_uom",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
