# Generated by Django 5.2.10 on 2026-08-03 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0025_user_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('PAYMENT', 'Payment Receipt'), ('DEPOSIT', 'Bank Deposit'), ('ORDER', 'Sales Order')], db_index=True, max_length=30)),
                ('company', models.CharField(blank=True, choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], default='', max_length=20)),
                ('restart_on_reject', models.BooleanField(default=True)),
                ('forbid_self_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_workflow',
                'ordering': ['document_type', 'company'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('document_number', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('total_levels', models.PositiveSmallIntegerField(default=0)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('level_entered_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='approvals.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('min_approvals', models.PositiveSmallIntegerField(default=1)),
                ('threshold_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_levels', to='users.userrole')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='approvals.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_level',
                'ordering': ['workflow_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevelApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_grants_made', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='approvals.approvallevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_level_approver',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_ala_user_active'), models.Index(fields=['level', 'is_active'], name='idx_ala_level_active')],
                'constraints': [models.UniqueConstraint(fields=('level', 'user', 'company'), name='approval_level_approver_uq')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('level_name', models.CharField(blank=True, default='', max_length=60)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('CANCEL', 'Cancelled'), ('RESUBMIT', 'Resubmitted')], max_length=12)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approver_username', models.CharField(blank=True, default='', max_length=150)),
                ('approver_role', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('acted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrequest')),
            ],
            options={
                'db_table': 'approval_action',
                'ordering': ['request_id', 'sequence'],
                'indexes': [models.Index(fields=['approver', '-acted_at'], name='idx_apact_user')],
                'constraints': [models.UniqueConstraint(fields=('request', 'sequence'), name='approval_action_seq_uq')],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('document_type', 'company'), name='approval_workflow_one_active_per_type_company'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'current_level'], name='idx_apreq_queue'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_apreq_target'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['company', 'status', '-created_at'], name='idx_apreq_list'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'PENDING'])), fields=('content_type', 'object_id'), name='approval_request_one_open_per_document'),
        ),
        migrations.AddConstraint(
            model_name='approvallevel',
            constraint=models.UniqueConstraint(fields=('workflow', 'sequence'), name='approval_level_seq_uq'),
        ),
    ]
