# Generated by Django 5.2.10 on 2026-08-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvallevel',
            name='threshold_hours',
        ),
    ]
