"""Create the BackDate module's own `backdate` PostgreSQL schema and tables.

No JSAP data is imported by this or any later migration. The module starts
empty; JSAP keeps its 1,093 requests / 996 flows / 1,335 actions for reference.
The BEHAVIOUR was migrated, the rows were not — see
`docs/migration/BKDT_TO_OMS_MIGRATION_PLAN.md` §20.
"""
# Generated by Django 5.2.10 on 2026-09-14 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0007_drop_runtime_and_testflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The dedicated Postgres schema must exist before any backdate"."
        # table is created. IF NOT EXISTS makes it safe to re-run; the reverse
        # drops it only once every table in it has been removed by the unwinds
        # above (CASCADE guards against a half-rolled-back state).
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS backdate;',
            reverse_sql='DROP SCHEMA IF EXISTS backdate CASCADE;',
        ),
        migrations.CreateModel(
            name='BackDateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], help_text='The SAP company the rights apply to.', max_length=20)),
                ('sap_username', models.CharField(help_text='The SAP user (OUSR.USER_CODE) being granted rights — not the OMS user raising the request.', max_length=50)),
                ('document_type', models.IntegerField(help_text='SAP object type (MOBJ.ObjType), e.g. 13 for A/R Invoice.')),
                ('from_date', models.DateField(help_text='Start of the back-posting window (inclusive).')),
                ('to_date', models.DateField(help_text='End of the back-posting window (inclusive).')),
                ('time_limit', models.DateTimeField(blank=True, help_text='When the granted rights lapse in SAP.', null=True)),
                ('action', models.CharField(choices=[('A', 'Add'), ('U', 'Update')], default='A', max_length=1)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backdate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BackDate Request',
                'db_table': 'backdate"."backdate_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackDateFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('current_sequence', models.PositiveSmallIntegerField(default=1)),
                ('hana_status', models.CharField(choices=[('NA', 'Not applicable'), ('PENDING', 'Awaiting write'), ('APPLIED', 'Applied'), ('FAILED', 'Failed')], default='NA', max_length=10)),
                ('hana_status_text', models.TextField(blank=True, default='')),
                ('hana_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_query', models.ForeignKey(blank=True, help_text='Which condition matched — the reason this workflow applies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflowquery')),
                ('workflow', models.ForeignKey(help_text='The workflow the engine selected at submission.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflow')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='backdate.backdaterequest')),
            ],
            options={
                'verbose_name': 'BackDate Flow',
                'db_table': 'backdate"."backdate_flow',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackDateApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.IntegerField(db_index=True)),
                ('stage_name', models.CharField(blank=True, default='', max_length=120)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='backdate.backdateflow')),
            ],
            options={
                'verbose_name': 'BackDate Approval Task',
                'db_table': 'backdate"."backdate_approval_task',
                'ordering': ['flow', 'sequence'],
                'indexes': [models.Index(fields=['status', 'stage_id'], name='bkdt_task_open_idx')],
                'constraints': [models.UniqueConstraint(fields=('flow', 'sequence'), name='bkdt_task_flow_seq_uq')],
            },
        ),
        migrations.CreateModel(
            name='BackDateApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Order within the flow, 1-based.')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('HANA_APPLIED', 'Rights applied in SAP'), ('HANA_FAILED', 'SAP write failed')], max_length=14)),
                ('stage_id', models.IntegerField(blank=True, null=True)),
                ('stage_name', models.CharField(blank=True, default='', max_length=120)),
                ('remarks', models.TextField(blank=True, default='')),
                ('acted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backdate_actions', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.ForeignKey(blank=True, help_text='The configured stage user, when a replacement acted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backdate_actions_on_behalf', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='backdate.backdateflow')),
            ],
            options={
                'verbose_name': 'BackDate Approval Action',
                'db_table': 'backdate"."backdate_approval_action',
                'ordering': ['flow', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('flow', 'sequence'), name='bkdt_action_flow_seq_uq')],
            },
        ),
        migrations.AddIndex(
            model_name='backdaterequest',
            index=models.Index(fields=['created_by', '-created_at'], name='bkdt_req_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='backdaterequest',
            index=models.Index(fields=['company'], name='bkdt_req_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='backdaterequest',
            constraint=models.CheckConstraint(condition=models.Q(('company__in', ['OIL', 'BEVERAGES', 'MART'])), name='backdate_request_company_valid'),
        ),
        migrations.AddConstraint(
            model_name='backdaterequest',
            constraint=models.CheckConstraint(condition=models.Q(('to_date__gte', models.F('from_date'))), name='backdate_request_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='backdateflow',
            index=models.Index(fields=['status'], name='bkdt_flow_status_idx'),
        ),
    ]
