"""`action` may say "both".

SAP never receives the action — `OPEN_BKDT` has no such parameter — so a
request for Add AND Update is one grant with a wider recorded scope, exactly as
JSAP stored it (`'A,U'` in a single `userDocument` row). Widening the column is
what lets the SAP row count follow COMPANIES rather than actions; splitting the
pair would write two rows identical in every column SAP reads.
"""
# Generated by Django 5.2.10 on 2026-09-15 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdate', '0002_require_time_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backdaterequest',
            name='action',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='backdaterequest',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['A', 'U', 'A,U'])), name='backdate_request_action_valid'),
        ),
    ]
