# Generated by Django 5.2.10 on 2026-09-22 06:26

"""A BackDate request may name several companies.

`company` becomes a canonical SET — `OIL`, `OIL,MART`, `OIL,BEVERAGES,MART` —
so one request can ask for the same rights in more than one SAP database while
staying one request, one flow and one approval chain. The SAP write already
fanned out per company (`services/hana.apply_grant`); only the input was
restricted.

BACKWARD COMPATIBLE, IN BOTH DIRECTIONS FOR EXISTING DATA. Every value already
in the column is a single code, and every single code is still a legal set, so
no row is rewritten and nothing needs backfilling. The CHECK widens from three
values to seven; it does not loosen into a pattern, so `MART,OIL` and
`OIL,OIL` remain refused by the database as they always were.

Reversing it is only safe while no row holds more than one company — the
narrower CHECK would refuse `OIL,MART`. Django will report that as a failed
constraint rather than dropping data.
"""
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdate', '0011_document_name_only_and_remarks_in_logs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='backdate',
            name='backdate_company_valid',
        ),
        migrations.AlterField(
            model_name='backdate',
            name='company',
            field=models.CharField(db_index=True, help_text='Companies whose SAP databases the rights are granted in, canonical and comma-separated (e.g. "OIL,MART").', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='backdate',
            constraint=models.CheckConstraint(condition=models.Q(('company__in', ['OIL', 'BEVERAGES', 'MART', 'OIL,BEVERAGES', 'OIL,MART', 'BEVERAGES,MART', 'OIL,BEVERAGES,MART'])), name='backdate_company_valid'),
        ),
    ]
