# Generated by Django 6.0.3 on 2026-06-10 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('POSTED_TO_SAP', 'Posted to SAP')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('invoice_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_log',
            },
        ),
    ]
