# Generated by Django 6.0.3 on 2026-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invociehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelog',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
