# Generated by Django 6.0.3 on 2026-06-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoicelog_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='invociehistory',
            name='invoice_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='invoice.invoicelog'),
        ),
    ]
