# Generated by Django 5.2.10 on 2026-06-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invociehistory_invoice_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRefLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=25)),
                ('card_name', models.CharField(max_length=255)),
                ('doc_date', models.DateField()),
                ('so_number', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('error_message', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_ref_logs',
            },
        ),
    ]
