# Generated by Django 5.2.10 on 2026-07-17 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoicelog_approved_by_invoicelog_ref_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelog',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='invoicelog',
            name='ref_id',
        ),
        migrations.RemoveField(
            model_name='invoicelog',
            name='rejected_by',
        ),
        migrations.AlterField(
            model_name='invoicelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ERROR', 'Error'), ('POSTED_TO_SAP', 'Posted to SAP')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='InvocieHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('invoice_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_history', to=settings.AUTH_USER_MODEL)),
                ('invoice_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='invoice.invoicelog')),
            ],
            options={
                'db_table': 'invoice_history',
            },
        ),
    ]
