# Generated by Django 5.2.10 on 2026-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_invoicelog_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited'), ('ERROR', 'Error'), ('POSTED_TO_SAP', 'Posted to SAP')], default='PENDING', max_length=20),
        ),
    ]
