# Generated by Django 5.2.10 on 2026-07-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_alter_invoicelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelog',
            name='branch',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='invoicelog',
            name='warehouse',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
