# Generated by Django 5.2.10 on 2026-07-21 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoicelog_branch_invoicelog_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited'), ('ERROR', 'Error'), ('POSTED_TO_SAP', 'Posted to SAP'), ('CL RAISED', 'CL Raised')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='CreditLimitLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsap_doc_id', models.IntegerField()),
                ('party_name', models.CharField(max_length=255)),
                ('credit_raised', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice_log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoicelog')),
            ],
        ),
    ]
