# Generated by Django 5.2.10 on 2026-07-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoicelog_status_creditlimitlogs'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creditlimitlogs',
            table='credit_limit_logs',
        ),
    ]
