# Generated by Django 5.2.10 on 2026-07-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_creditlimitlogs_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditlimitlogs',
            name='credit_raised',
        ),
    ]
