# Generated by Django 5.2.10 on 2026-07-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_remove_creditlimitlogs_credit_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited'), ('ERROR', 'Error'), ('POSTED_TO_SAP', 'Posted to SAP'), ('CL_RAISED', 'CL Raised')], default='PENDING', max_length=20),
        ),
    ]
