# Generated by Django 5.2.10 on 2026-07-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_invoicelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invociehistory',
            name='created_by',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
