# Generated by Django 5.2.10 on 2026-07-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_invoicelog_supersedes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditlimitlogs',
            name='id',
        ),
        migrations.AlterField(
            model_name='creditlimitlogs',
            name='invoice_log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='invoice.invoicelog'),
            preserve_default=False,
        ),
    ]
