# Generated by Django 5.2.10 on 2026-08-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_invoicelog_sap_doc_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invociehistory',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invociehistory',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
