# Generated by Django 5.2.10 on 2026-09-24 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.PositiveIntegerField(blank=True, help_text="JSAP's EmployeeId; empty for an employee added in OMS.", null=True, unique=True)),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('employee_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'HOD'), (2, 'Sub-HOD'), (3, 'Executive')], default=3)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advance_payment_employee',
                'ordering': ['employee_name'],
                'indexes': [models.Index(fields=['role'], name='ap_employee_role_idx'), models.Index(fields=['is_active', 'is_deleted'], name='ap_employee_state_idx')],
            },
        ),
    ]
