# Generated by Django 5.2.10 on 2026-09-24 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0002_load_jsap_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'advance_payment_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_departments', to='advance_payment.department')),
            ],
            options={
                'db_table': 'advance_payment_sub_department',
                'ordering': ['department__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('department', 'name'), name='ap_sub_department_name_uq')],
            },
        ),
    ]
