# Generated by Django 5.2.10 on 2026-09-24 13:19

import advance_payment.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0004_load_jsap_departments'),
        ('workflow', '0007_drop_runtime_and_testflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('request_type', models.CharField(choices=[('VENDOR', 'Vendor'), ('EMPLOYEE_ADVANCE', 'Employee'), ('EMPLOYEE_IMPREST', 'Employee Imprest')], max_length=20)),
                ('payment_against', models.CharField(choices=[('ADVANCE', 'Advance'), ('AGAINST_BILL', 'Against Bill'), ('AGAINST_PO', 'Against PO'), ('ALL', 'All'), ('OTHER', 'Other')], max_length=20)),
                ('payment_against_other', models.CharField(blank=True, default='', max_length=120)),
                ('partner_code', models.CharField(max_length=50)),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_not_in_sap', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('expected_date', models.DateField(blank=True, help_text='Against PO: Expected Bill Date.', null=True)),
                ('expected_bill_date', models.DateField(blank=True, help_text='Employee Imprest.', null=True)),
                ('return_method', models.CharField(blank=True, choices=[('ONE_TIME', 'One Time'), ('EMI', 'EMI'), ('CUSTOM', 'Other / Custom')], default='', max_length=20)),
                ('return_method_other', models.CharField(blank=True, default='', max_length=120)),
                ('installments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('expected_from_date', models.DateField(blank=True, null=True)),
                ('expected_to_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('owner_label', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('IN_APPROVAL', 'In approval'), ('RETURNED', 'Returned to creator'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='IN_APPROVAL', max_length=20)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_requests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='advance_payment.department')),
                ('owner_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_requests', to='advance_payment.employee')),
                ('sub_department', models.ForeignKey(blank=True, help_text='Empty for a department that has no sub-departments.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='advance_payment.subdepartment')),
            ],
            options={
                'db_table': 'advance_payment_request',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('to_account_number', models.CharField(blank=True, default='', max_length=40)),
                ('to_ifsc', models.CharField(blank=True, default='', max_length=11)),
                ('to_account_manual', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='advance_payment.advancerequest')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advance_payment_payout',
            },
        ),
        migrations.CreateModel(
            name='PayoutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('UPI', 'UPI'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('IMPS', 'IMPS'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('from_account', models.CharField(max_length=30)),
                ('from_account_label', models.CharField(blank=True, default='', max_length=200)),
                ('cheque_number', models.CharField(blank=True, default='', max_length=20)),
                ('cheque_bank', models.CharField(blank=True, default='', max_length=100)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cash_notes', models.JSONField(blank=True, default=None, null=True)),
                ('utr', models.CharField(blank=True, default='', max_length=30)),
                ('utr_proof', models.JSONField(blank=True, default=None, null=True)),
                ('utr_recorded_on', models.DateTimeField(blank=True, null=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='advance_payment.payout')),
                ('utr_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advance_payment_payout_line',
                'ordering': ['payout', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BILL', 'A/P invoice'), ('PO', 'Purchase order'), ('OTHER', 'Other open document')], max_length=10)),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('sap_doc_type', models.CharField(blank=True, default='', max_length=60)),
                ('vendor_ref', models.CharField(blank=True, default='', max_length=100)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('open_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('mode', models.CharField(choices=[('FIXED', 'Fixed amount'), ('PERCENT', 'Percentage')], default='FIXED', max_length=10)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('attachment_file', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_check', models.JSONField(blank=True, default=None, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='advance_payment.advancerequest')),
            ],
            options={
                'db_table': 'advance_payment_request_document',
                'ordering': ['request', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('SUPPORTING', 'Supporting document'), ('BANK_PROOF', 'Bank proof'), ('PAYMENT_PROOF', 'Payment proof')], max_length=20)),
                ('file', models.FileField(max_length=500, upload_to=advance_payment.models._request_file_path)),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('payout_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='advance_payment.payoutline')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='advance_payment.advancerequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advance_payment_request_file',
                'ordering': ['request', 'uploaded_on'],
            },
        ),
        migrations.CreateModel(
            name='RequestFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RETURNED', 'Returned to creator'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('current_role', models.CharField(blank=True, choices=[('SUB_HOD', 'Sub-HOD Approval'), ('HOD', 'HOD Approval'), ('DIRECTOR', 'Director Approval'), ('PAYMENT', 'Payment Approval'), ('AUDIT', 'Audit Approval'), ('FINAL', 'Final Approval')], default='', max_length=10)),
                ('total_stages', models.PositiveSmallIntegerField(default=0)),
                ('cycle', models.PositiveSmallIntegerField(default=1)),
                ('edited_since_audit', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
                ('current_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowquery')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow', to='advance_payment.advancerequest')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflow.workflow')),
            ],
            options={
                'db_table': 'advance_payment_request_flow',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('EDITED', 'Edited'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned to creator'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back to Payment'), ('PAYOUT_UPDATED', 'Payment details updated'), ('PARTNER_LINKED', 'Linked to its SAP account'), ('SAP_POSTED', 'Voucher posted to SAP'), ('SAP_POST_FAILED', 'Voucher failed to post'), ('SAP_CANCELLED', 'Voucher cancelled in SAP'), ('SAP_REPOSTED', 'Voucher re-posted to SAP'), ('UTR_RECORDED', 'UTR recorded'), ('FILE_ADDED', 'File added'), ('COMPLETED', 'Completed')], max_length=20)),
                ('cycle', models.PositiveSmallIntegerField(default=1)),
                ('stage_name', models.CharField(blank=True, default='', max_length=120)),
                ('stage_sequence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=None, null=True)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('on_behalf_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='advance_payment.advancerequest')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstage')),
            ],
            options={
                'db_table': 'advance_payment_request_log',
                'ordering': ['created_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SapVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('sap_object', models.CharField(choices=[('OUTGOING_PAYMENT', 'Outgoing payment (OVPM)'), ('JOURNAL_ENTRY', 'Journal entry (OJDT)')], max_length=20)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=10)),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=None, null=True)),
                ('response', models.JSONField(blank=True, default=None, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_on', models.DateTimeField(blank=True, null=True)),
                ('cancel_doc_entry', models.IntegerField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='advance_payment.sapvoucher')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='advance_payment.advancerequest')),
            ],
            options={
                'db_table': 'advance_payment_sap_voucher',
                'ordering': ['request', 'version'],
            },
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['company', 'status'], name='ap_request_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['department', 'sub_department'], name='ap_request_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='advancerequest',
            index=models.Index(fields=['created_by', 'status'], name='ap_request_creator_idx'),
        ),
        migrations.AddConstraint(
            model_name='advancerequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ap_request_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payoutline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ap_payout_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='requestdocument',
            constraint=models.UniqueConstraint(fields=('request', 'kind', 'sap_doc_entry'), name='ap_request_document_once'),
        ),
        migrations.AddConstraint(
            model_name='requestdocument',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ap_request_document_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='requestdocument',
            constraint=models.CheckConstraint(condition=models.Q(('amount__lte', models.F('open_amount'))), name='ap_request_document_within_open'),
        ),
        migrations.AddIndex(
            model_name='requestflow',
            index=models.Index(fields=['status', 'current_user'], name='ap_flow_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='requestflow',
            index=models.Index(fields=['current_stage'], name='ap_flow_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='requestflow',
            index=models.Index(fields=['workflow'], name='ap_flow_workflow_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['request', 'created_on'], name='ap_log_request_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['request', 'cycle', 'action'], name='ap_log_cycle_action_idx'),
        ),
        migrations.AddConstraint(
            model_name='sapvoucher',
            constraint=models.UniqueConstraint(fields=('request', 'version'), name='ap_voucher_version_uq'),
        ),
        migrations.AddConstraint(
            model_name='sapvoucher',
            constraint=models.UniqueConstraint(condition=models.Q(('replaced_by__isnull', True), ('status', 'POSTED')), fields=('request',), name='ap_voucher_one_live'),
        ),
    ]
