# Generated by Django 5.2.10 on 2026-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0005_payment_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestdocument',
            name='attachment_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requestdocument',
            name='attachment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('EDITED', 'Edited'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned to creator'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back to Payment'), ('PAYOUT_UPDATED', 'Payment details updated'), ('PARTNER_LINKED', 'Linked to its SAP account'), ('SAP_POSTED', 'Voucher posted to SAP'), ('SAP_POST_FAILED', 'Voucher failed to post'), ('SAP_CANCELLED', 'Voucher cancelled in SAP'), ('SAP_REPOSTED', 'Voucher re-posted to SAP'), ('UTR_RECORDED', 'UTR recorded'), ('FILE_ADDED', 'File added'), ('FILE_REMOVED', 'File removed'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
