# Generated by Django 5.2.10 on 2026-09-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0006_request_document_attachment_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestflow',
            name='current_role',
            field=models.CharField(blank=True, choices=[('APPROVAL', 'Approval'), ('PAYMENT', 'Payment Approval'), ('AUDIT', 'Audit Approval'), ('FINAL', 'Final Approval')], default='', max_length=10),
        ),
    ]
