# Generated by Django 5.2.10 on 2026-09-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0008_seed_advance_payment_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='budget_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='budget_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='sub_budget_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='sub_budget_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
