# Generated by Django 5.2.10 on 2026-10-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0014_request_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='department_head_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='headed_requests', to='advance_payment.employee'),
        ),
    ]
