# Generated by Django 5.2.10 on 2026-10-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0015_request_department_head_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='effect_month',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='expense_tds_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='is_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='payment_against',
            field=models.CharField(choices=[('ADVANCE', 'Advance'), ('AGAINST_BILL', 'Against Bill'), ('AGAINST_PO', 'Against PO'), ('ALL', 'All'), ('AGAINST_LEDGER', 'Against Ledger'), ('ON_ACCOUNT', 'On Account'), ('OTHER', 'Other'), ('DIRECT_EXPENSE', 'Direct Expense'), ('INDIRECT_EXPENSE', 'Indirect Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='request_type',
            field=models.CharField(choices=[('VENDOR', 'Vendor'), ('EMPLOYEE_ADVANCE', 'Employee'), ('EMPLOYEE_IMPREST', 'Employee Imprest'), ('CUSTOMER', 'Customer'), ('EXPENSE', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('EDITED', 'Edited'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned to creator'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back to Payment'), ('PAYOUT_UPDATED', 'Payment details updated'), ('PAYMENT_EDITED', 'Edited at Payment'), ('PARTNER_LINKED', 'Linked to its SAP account'), ('SAP_POSTED', 'Voucher posted to SAP'), ('SAP_POST_FAILED', 'Voucher failed to post'), ('SAP_CANCELLED', 'Voucher cancelled in SAP'), ('SAP_REPOSTED', 'Voucher re-posted to SAP'), ('UTR_RECORDED', 'UTR recorded'), ('FILE_ADDED', 'File added'), ('FILE_REMOVED', 'File removed'), ('COMPLETED', 'Completed')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('gst_code', models.CharField(blank=True, default='', max_length=20)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('gl_account', models.CharField(blank=True, default='', max_length=20)),
                ('gl_name', models.CharField(blank=True, default='', max_length=200)),
                ('effect_month', models.CharField(blank=True, default='', max_length=20)),
                ('remarks', models.CharField(blank=True, default='', max_length=254)),
                ('tds_override', models.CharField(blank=True, default='', max_length=20)),
                ('tds_code', models.CharField(blank=True, default='', max_length=20)),
                ('tds_label', models.CharField(blank=True, default='', max_length=150)),
                ('tds_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tds_account', models.CharField(blank=True, default='', max_length=20)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_lines', to='advance_payment.advancerequest')),
            ],
            options={
                'db_table': 'advance_payment_expense_line',
                'ordering': ['request', 'line_no'],
                'constraints': [models.UniqueConstraint(fields=('request', 'line_no'), name='ap_expense_line_once'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ap_expense_line_amount_positive')],
            },
        ),
    ]
