# Generated by Django 5.2.10 on 2026-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payment', '0017_payout_sap_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfile',
            name='sap_attachment_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestfile',
            name='share_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='requestfile',
            name='share_file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestfile',
            name='share_folder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestfile',
            name='share_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sapvoucher',
            name='attachment_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sapvoucher',
            name='attachment_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('EDITED', 'Edited'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned to creator'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent back to Payment'), ('PAYOUT_UPDATED', 'Payment details updated'), ('PAYMENT_EDITED', 'Edited at Payment'), ('PARTNER_LINKED', 'Linked to its SAP account'), ('SAP_POSTED', 'Voucher posted to SAP'), ('SAP_POST_FAILED', 'Voucher failed to post'), ('SAP_CANCELLED', 'Voucher cancelled in SAP'), ('SAP_REPOSTED', 'Voucher re-posted to SAP'), ('UTR_RECORDED', 'UTR recorded'), ('FILE_ADDED', 'File added'), ('FILE_REMOVED', 'File removed'), ('SAP_ATTACHED', 'Files attached in SAP'), ('COMPLETED', 'Completed')], max_length=20),
        ),
    ]
