# Generated by Django 5.2.10 on 2026-07-13 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'tracker_branch',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'tracker_category',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GstRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tracker_gst_rate',
                'ordering': ['sort_order', 'rate'],
            },
        ),
        migrations.CreateModel(
            name='GstType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tracker_gst_type',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tracker_mode',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('threshold_days', models.PositiveIntegerField(default=3)),
                ('status_choices', models.JSONField(blank=True, default=list)),
                ('requires_status', models.BooleanField(default=False)),
                ('can_return', models.BooleanField(default=True)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tracker_stage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tracker_unit',
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('party_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=100)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('current_stage_entered_at', models.DateTimeField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tracker.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tracker.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracker_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('gst_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tracker.gstrate')),
                ('gst_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tracker.gsttype')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tracker.invoicemode')),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_invoices', to='tracker.stage')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tracker.unit')),
            ],
            options={
                'db_table': 'tracker_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid')], default='OPEN', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tracker.invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_payments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_payment_detail',
            },
        ),
        migrations.CreateModel(
            name='TransporterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_bill_no', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=255)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tds_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_transporter_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_transporter_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=100)),
                ('voucher_date', models.DateField()),
                ('details', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_cash_vouchers', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_vouchers', to='tracker.unit')),
            ],
            options={
                'db_table': 'tracker_cash_voucher',
                'ordering': ['-voucher_date'],
            },
        ),
        migrations.CreateModel(
            name='UserStageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_stage_access_granted', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='tracker.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_stage_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_user_stage_access',
                'ordering': ['user_id', 'stage__order'],
            },
        ),
        migrations.CreateModel(
            name='StageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RECEIVE', 'Received'), ('ADVANCE', 'Advanced'), ('RETURN', 'Returned')], max_length=10)),
                ('stage_status', models.CharField(blank=True, default='', max_length=30)),
                ('receiving_note', models.CharField(blank=True, choices=[('ON_TIME', 'On time'), ('LATE', 'Late received (After 6 PM)')], default='', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('days_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_stage_events', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.invoice')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tracker.stage')),
            ],
            options={
                'db_table': 'tracker_stage_event',
                'ordering': ['invoice_id', 'entered_at'],
                'indexes': [models.Index(fields=['invoice', 'stage'], name='tracker_sta_invoice_46fb16_idx'), models.Index(fields=['stage', 'event_type'], name='tracker_sta_stage_i_d95d92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['current_stage', 'status'], name='tracker_inv_current_612b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='tracker_inv_invoice_3bd1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['party_name'], name='tracker_inv_party_n_fdefdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstageaccess',
            unique_together={('user', 'stage')},
        ),
    ]
