# Generated by Django 5.2.10 on 2026-07-13 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuckAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_entered_at', models.DateTimeField()),
                ('days_stuck', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('threshold_days', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracker.invoice')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracker.stage')),
            ],
            options={
                'db_table': 'tracker_stuck_alert',
                'ordering': ['-days_stuck'],
                'indexes': [models.Index(fields=['is_active', 'stage'], name='tracker_stu_is_acti_dd41a0_idx')],
                'unique_together': {('invoice', 'stage', 'stage_entered_at')},
            },
        ),
    ]
