# Generated by Django 5.2.10 on 2026-07-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_stuckalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_charge_type',
            field=models.CharField(blank=True, choices=[('DEMURRAGE', 'Demurrage'), ('LABOUR_COST', 'Labour Cost'), ('POINT_VALUE', 'Point Value')], default='', max_length=20),
        ),
    ]
