# Generated by Django 5.2.10 on 2026-07-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_invoice_additional_charge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stageevent',
            name='hold_type',
            field=models.CharField(blank=True, choices=[('FULL', 'Full hold (work on it later)'), ('PARTIAL', 'Partial hold (portion of value)')], default='', max_length=10),
        ),
    ]
