# Generated by Django 5.2.10 on 2026-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_stageevent_amount_stageevent_hold_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='party_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='party_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
