# Generated by Django 5.2.10 on 2026-07-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_invoice_party_code_invoice_party_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
