# Generated by Django 5.2.10 on 2026-07-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_invoice_deleted_at_invoice_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuckalert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
