# Generated by Django 5.2.10 on 2026-07-21 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_stuckalert_last_notified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('days_stuck', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sent_at', models.DateTimeField()),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tracker.stuckalert')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to='tracker.invoice')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to='tracker.stage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_alert_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracker_alert_notification',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['invoice', 'user'], name='tracker_ale_invoice_f08fb1_idx'), models.Index(fields=['sent_at'], name='tracker_ale_sent_at_4559e6_idx')],
            },
        ),
    ]
