# Generated by Django 5.2.10 on 2026-07-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alertnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rejection_pending',
            field=models.BooleanField(default=False),
        ),
    ]
