# Generated by Django 5.2.10 on 2026-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_invoice_effective_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='tds_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
