# Generated by Django 5.2.10 on 2026-07-25 12:42

from django.db import migrations, models
from django.db.models import Sum


def backfill_debit_and_hold(apps, schema_editor):
    """Populate debit_amount / hold_amount on existing invoices from their past
    stage events, so historical invoices reflect prior debits and partial holds.
    A DEBIT event carries the debit amount; a PARTIAL hold event carries the
    held amount. Both were only recorded on StageEvent before these fields."""
    Invoice = apps.get_model('tracker', 'Invoice')
    StageEvent = apps.get_model('tracker', 'StageEvent')

    debits = dict(
        StageEvent.objects.filter(stage_status__iexact='DEBIT', amount__isnull=False)
        .values_list('invoice_id').annotate(total=Sum('amount'))
    )
    holds = dict(
        StageEvent.objects.filter(hold_type='PARTIAL', amount__isnull=False)
        .values_list('invoice_id').annotate(total=Sum('amount'))
    )
    for inv_id in set(debits) | set(holds):
        Invoice.objects.filter(pk=inv_id).update(
            debit_amount=debits.get(inv_id, 0) or 0,
            hold_amount=holds.get(inv_id, 0) or 0,
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_invoice_debit_amount_paymentdetail_discount_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hold_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='hold_added_back',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_debit_and_hold, noop),
    ]
