# Generated by Django 5.2.10 on 2026-08-19 06:41

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_remove_transport_approval_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('invoice_number'), condition=models.Q(('is_deleted', False)), name='uniq_live_invoice_number'),
        ),
    ]
