# Generated by Django 5.2.10 on 2026-08-19 07:00

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_alter_invoice_invoice_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='uniq_live_invoice_number',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.NullIf(django.db.models.functions.text.Lower('party_code'), models.Value('')), django.db.models.functions.text.Lower('party_name')), django.db.models.functions.text.Lower('invoice_number'), condition=models.Q(('is_deleted', False)), name='uniq_live_vendor_invoice_number'),
        ),
    ]
