# Generated by Django 5.2.10 on 2026-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_seed_tracker_ap_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageevent',
            name='event_type',
            field=models.CharField(choices=[('RECEIVE', 'Received'), ('ADVANCE', 'Advanced'), ('RETURN', 'Returned'), ('NOTE', 'Note')], max_length=10),
        ),
    ]
