# Generated by Django 5.2.10 on 2026-08-27 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_alter_stageevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stageevent',
            constraint=models.UniqueConstraint(condition=models.Q(('exited_at__isnull', True), models.Q(('event_type', 'NOTE'), _negated=True)), fields=('invoice', 'stage'), name='tracker_stage_event_one_open_visit_per_stage'),
        ),
    ]
