# Generated by Django 5.2.10 on 2026-08-14 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0028_merge_0026_hais_role_0027_payment_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='framework_notifications', to='users.company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'public"."notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='nfw_user_created_idx'), models.Index(fields=['user', 'is_read'], name='nfw_user_read_idx'), models.Index(fields=['company', '-created_at'], name='nfw_company_created_idx'), models.Index(fields=['content_type', 'object_id'], name='nfw_entity_idx')],
            },
        ),
    ]
